import { useCallback, useState } from "react"
import { IconAlertTriangle, IconChartBar, IconClick, IconEye, IconInfoCircle, IconUsers } from "@tabler/icons-react"
import { useLocation, useNavigate } from "react-router-dom"

import { Alert, AlertDescription, AlertTitle, Button, EditorSection, IconBox, LoadingRows, PageFrame, PageState, Progress, StatusBadge } from "@crm/ui"

import { PageHeading, SegmentedControl } from "@admin/components/cms-ui"
import { cmsRepository } from "@admin/data/cms-repository"
import { useRepository } from "@admin/features/use-repository"
import { formatPercentOf } from "@admin/lib/analytics-format"

const number = new Intl.NumberFormat("ru-RU")
const tabs = [{ path: "/analytics", label: "Обзор" }, { path: "/analytics/acquisition", label: "Источники" }, { path: "/analytics/content", label: "Контент" }, { path: "/analytics/funnels", label: "Воронки" }, { path: "/analytics/forms", label: "Формы" }, { path: "/analytics/retention", label: "Retention" }, { path: "/analytics/quality", label: "Качество" }]

export function AnalyticsPage() {
  const loader = useCallback(() => cmsRepository.getAnalytics(), []); const state = useRepository(loader); const location = useLocation(); const navigate = useNavigate(); const [period, setPeriod] = useState<"month" | "quarter">("month"); const current = tabs.find((tab) => tab.path === location.pathname)?.label ?? "Обзор"
  if (state.error) return <PageFrame><PageState actionLabel="Повторить" icon={IconAlertTriangle} onAction={state.reload} title="Аналитика пока недоступна">{state.error}</PageState></PageFrame>
  if (state.loading || !state.data) return <PageFrame><LoadingRows count={6} /></PageFrame>
  const data = state.data
  return <PageFrame><PageHeading actions={<SegmentedControl ariaLabel="Период" onChange={setPeriod} options={[{ value: "month", label: "Месяц" }, { value: "quarter", label: "Квартал" }]} value={period} />} description={`${data.period} · first-party aggregates · server conversion facts`} title="Аналитика" /><div className="mb-3 flex gap-1 overflow-x-auto rounded-xl border bg-background p-1">{tabs.map((tab) => <Button className="shrink-0" key={tab.path} onClick={() => navigate(tab.path)} size="sm" variant={location.pathname === tab.path ? "secondary" : "ghost"}>{tab.label}</Button>)}</div><Alert className="mb-3 border-info/25"><IconInfoCircle /><AlertTitle>Приватность по умолчанию</AlertTitle><AlertDescription>Opaque visitor/session IDs; raw IP, contacts, form values и cookies не попадают в analytics events. Метрика — consent-gated comparative aggregate.</AlertDescription></Alert>{current === "Воронки" ? <Funnel data={data} /> : current === "Источники" ? <Channels data={data} /> : current === "Контент" ? <ContentAnalytics data={data} /> : current === "Качество" ? <Quality /> : <Overview data={data} section={current} />}</PageFrame>
}

type Analytics = Awaited<ReturnType<typeof cmsRepository.getAnalytics>>
function Metrics({ data }: { data: Analytics }) { const items = [{ label: "Посетители", value: data.visitors, icon: IconUsers }, { label: "Просмотры", value: data.views, icon: IconEye }, { label: "Заявки", value: data.leads, icon: IconClick }, { label: "Оплачено", value: data.paid, icon: IconChartBar }]; return <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{items.map((item) => <div className="rounded-xl border bg-background p-4" key={item.label}><div className="flex items-center gap-3"><IconBox icon={item.icon} size="sm" variant="info" /><span className="text-[10px] text-muted-foreground">{item.label}</span></div><p className="mt-3 text-xl font-semibold tabular-nums">{number.format(item.value)}</p></div>)}</div> }
function Overview({ data, section }: { data: Analytics; section: string }) { return <div className="space-y-3"><Metrics data={data} />{section !== "Обзор" ? <EditorSection title={section}><p className="text-xs text-muted-foreground">Представительный shell вкладки: детальные cohort/form metrics подключатся после authoritative analytics API P4.7.</p></EditorSection> : <div className="grid gap-3 lg:grid-cols-2"><Channels data={data} /><Funnel data={data} /></div>}<ContentAnalytics data={data} /></div> }
function Channels({ data }: { data: Analytics }) { return <EditorSection title="Источники"><div className="space-y-3">{data.channels.map((channel) => <div key={channel.name}><div className="mb-1 flex justify-between text-[10px]"><span>{channel.name}</span><span>{number.format(channel.value)} · {channel.percent}%</span></div><Progress value={channel.percent} /></div>)}</div></EditorSection> }
function Funnel({ data }: { data: Analytics }) { const steps = [{ label: "Visitors", value: data.visitors }, { label: "Leads", value: data.leads }, { label: "Confirmed bookings", value: data.bookings }, { label: "Paid", value: data.paid }]; return <EditorSection subtitle="Lead → Booking → Payment — server facts, не browser guesses." title="Воронка"><div className="space-y-2">{steps.map((step, index) => <div className="flex items-center gap-3 rounded-lg border px-3 py-3" key={step.label}><span className="flex size-6 items-center justify-center rounded-full bg-primary/10 text-[10px] font-semibold text-primary">{index + 1}</span><span className="min-w-0 flex-1 text-xs">{step.label}</span><strong className="tabular-nums">{number.format(step.value)}</strong>{index ? <StatusBadge tone="info">{formatPercentOf(step.value, steps[index - 1]!.value)}</StatusBadge> : null}</div>)}</div></EditorSection> }
function ContentAnalytics({ data }: { data: Analytics }) { return <EditorSection title="Страницы и секции"><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead className="border-b text-[10px] text-muted-foreground"><tr><th className="pb-2">URL</th><th>Views</th><th>CTA clicks</th><th>Leads</th><th>CVR</th></tr></thead><tbody className="divide-y">{data.pages.map((page) => <tr key={page.path}><td className="py-3 font-mono text-xs">{page.path}</td><td>{number.format(page.views)}</td><td>{number.format(page.cta)}</td><td>{number.format(page.leads)}</td><td>{formatPercentOf(page.leads, page.views)}</td></tr>)}</tbody></table></div></EditorSection> }
function Quality() { return <EditorSection title="Качество сбора"><div className="grid gap-3 sm:grid-cols-3">{[["События приняты", "99.4%", "success"], ["Bot/internal excluded", "8.2%", "info"], ["Metrika delta", "+3.1%", "warning"]].map(([label, value, tone]) => <div className="rounded-lg border p-3" key={label}><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-2 text-lg font-semibold">{value}</p><StatusBadge className="mt-2" tone={tone as "success" | "info" | "warning"}>В пределах</StatusBadge></div>)}</div></EditorSection> }
