import { useCallback, useState } from "react"
import { IconAlertTriangle, IconBraces, IconChevronRight, IconCode, IconDeviceDesktop, IconEye, IconFile, IconFileTypeCss, IconJson, IconFolder, IconGitBranch, IconLock, IconPackage, IconPlayerPlay, IconShieldCheck } from "@tabler/icons-react"
import { useParams, useSearchParams } from "react-router-dom"

import { Alert, AlertDescription, AlertTitle, Button, EditorSection, LoadingRows, PageFrame, PageNav, PageState, StatusBadge, Textarea, cn } from "@crm/ui"

import { PageHeading, ReleaseGateRow } from "@admin/components/cms-ui"
import { cmsRepository } from "@admin/data/cms-repository"
import type { CodeArtifact } from "@admin/entities/cms"
import { useRepository } from "@admin/features/use-repository"

const tabs = [{ value: "files", label: "Files" }, { value: "diff", label: "Diff" }, { value: "preview", label: "Preview" }, { value: "build", label: "Build" }, { value: "dependencies", label: "Dependencies" }, { value: "media", label: "Media usage" }, { value: "history", label: "History" }]

export function CodePage() {
  const { artifactId } = useParams(); const loader = useCallback(() => cmsRepository.getCodeArtifact(artifactId), [artifactId]); const state = useRepository(loader); const [params, setParams] = useSearchParams(); const tab = params.get("tab") ?? "files"; const [source, setSource] = useState<string>(); const [dirty, setDirty] = useState(false); const [building, setBuilding] = useState(false); const [selected, setSelected] = useState("src/sections/HomepageFeatured.tsx")
  if (state.error) return <PageFrame width="full"><PageState actionLabel="Повторить" icon={IconAlertTriangle} onAction={state.reload} title="Редактор кода пока недоступен">{state.error}</PageState></PageFrame>
  if (state.loading || !state.data) return <PageFrame width="full"><LoadingRows count={8} /></PageFrame>
  const artifact = state.data; const displayedSource = source ?? artifact.source
  const runBuild = () => { setBuilding(true); window.setTimeout(() => setBuilding(false), 1800) }
  return <PageFrame width="full"><PageHeading actions={<><Button onClick={() => window.alert("Предпросмотр открыт") } size="sm" variant="outline"><IconEye />Предпросмотр</Button><Button disabled={!dirty} onClick={() => { setDirty(false); window.alert("Черновик сохранён; сайт пока не изменён") }} size="sm">Сохранить</Button></>} description="Безопасное редактирование разрешённых файлов сайта с автоматической проверкой перед публикацией." title="Файлы и код" /><Alert className="mb-3 border-info/25"><IconShieldCheck /><AlertTitle>Защищённая рабочая область</AlertTitle><AlertDescription>Черновик обновляется в предпросмотре сразу. На публичный сайт код попадает только после автоматических проверок.</AlertDescription></Alert><div className="mb-3 overflow-hidden rounded-xl border bg-background px-3"><PageNav items={tabs} onValueChange={(next) => { const copy = new URLSearchParams(params); copy.set("tab", next); setParams(copy, { replace: true }) }} value={tab} /></div>
    {tab === "files" ? <FilesView artifact={artifact} dirty={dirty} onChange={(value) => { setSource(value); setDirty(true) }} onSelect={setSelected} selected={selected} source={displayedSource} /> : tab === "diff" ? <DiffView artifact={artifact} /> : tab === "preview" ? <PreviewView artifact={artifact} /> : tab === "build" ? <BuildView artifact={artifact} building={building} onBuild={runBuild} /> : tab === "dependencies" || tab === "media" ? <Dependencies artifact={artifact} media={tab === "media"} /> : <History />}
  </PageFrame>
}

function FilesView({ artifact, dirty, onChange, onSelect, selected, source }: { artifact: CodeArtifact; dirty: boolean; onChange: (value: string) => void; onSelect: (path: string) => void; selected: string; source: string }) { return <div className="grid min-h-[640px] overflow-hidden rounded-xl border bg-background lg:grid-cols-[270px_minmax(420px,1fr)_320px]"><FileTree artifact={artifact} onSelect={onSelect} selected={selected} /><section className="min-w-0 border-b lg:border-b-0 lg:border-x"><div className="flex min-h-11 items-center gap-2 border-b px-3"><IconCode className="size-4 text-primary" /><span className="min-w-0 flex-1 truncate font-mono text-[11px]">{selected}</span>{dirty ? <StatusBadge tone="warning">Modified</StatusBadge> : <StatusBadge tone="success">Saved</StatusBadge>}</div><div className="relative"><div className="absolute inset-y-0 left-0 w-10 select-none border-r bg-muted/25 py-3 text-right font-mono text-[11px] leading-5 text-muted-foreground" aria-hidden>{Array.from({ length: 18 }, (_, index) => <span className="block pr-2" key={index}>{index + 1}</span>)}</div><Textarea aria-label="Исходный код artifact" className="admin-code-scroll min-h-[580px] resize-none rounded-none border-0 bg-neutral-950 py-3 pl-12 font-mono text-[11px] leading-5 text-neutral-100 focus-visible:ring-0 max-lg:hidden" onChange={(event) => onChange(event.target.value)} value={source} /><pre className="admin-code-scroll min-h-[360px] overflow-auto bg-neutral-950 p-4 pl-12 font-mono text-[11px] leading-5 text-neutral-100 lg:hidden">{source}</pre></div><div className="flex min-h-10 items-center gap-2 border-t px-3 text-[10px] text-muted-foreground"><IconDeviceDesktop className="size-3" /><span className="max-lg:hidden">Editable on desktop with canManageSiteCode</span><span className="lg:hidden">Mobile browse/diff is read-only</span></div></section><Inspector artifact={artifact} /></div> }
function FileTree({ artifact, onSelect, selected }: { artifact: CodeArtifact; onSelect: (path: string) => void; selected: string }) { return <aside className="min-w-0 border-b lg:border-b-0"><div className="flex h-11 items-center border-b px-3"><h3 className="text-[11px] font-semibold uppercase tracking-[.06em]">Allowlisted files</h3><StatusBadge className="ml-auto" tone="info">Git draft</StatusBadge></div><div className="max-h-64 overflow-auto p-2 lg:max-h-[590px]">{artifact.files.map((file) => { const Icon = file.kind === "folder" ? IconFolder : file.kind === "css" ? IconFileTypeCss : file.kind === "json" ? IconJson : IconFile; const depth = file.path.split("/").length - 1; return <Button className={cn("mb-0.5 h-8 w-full justify-start px-2 text-[11px]", selected === file.path && "bg-accent")} key={file.path} onClick={() => file.kind !== "folder" && onSelect(file.path)} style={{ paddingLeft: 8 + depth * 10 }} variant="ghost">{file.kind === "folder" ? <IconChevronRight className="size-3" /> : null}<Icon className="size-3.5" /><span className="min-w-0 flex-1 truncate text-left">{file.path.split("/").at(-1)}</span>{file.changed ? <span className="size-1.5 rounded-full bg-warning" /> : null}</Button> })}</div><div className="border-t p-3"><p className="flex items-center gap-1 text-[10px] text-muted-foreground"><IconLock className="size-3" />Blocked: .env, config, DB, migrations, package manager</p></div></aside> }
function Inspector({ artifact }: { artifact: CodeArtifact }) { return <aside className="min-w-0 p-3"><h3 className="text-[11px] font-semibold uppercase tracking-[.06em] text-muted-foreground">Artifact inspector</h3><div className="mt-3 space-y-2">{artifact.gates.map((gate) => <div className="rounded-lg border" key={gate.id}><ReleaseGateRow gate={gate} /></div>)}</div><h4 className="mt-4 text-[11px] font-semibold">Dependencies & usage</h4><div className="mt-2 divide-y rounded-lg border">{artifact.dependencies.map((dependency) => <div className="flex min-h-10 items-center gap-2 px-3 text-[10px]" key={dependency}><IconPackage className="size-3.5 text-muted-foreground" /><span className="truncate">{dependency}</span></div>)}</div></aside> }
function DiffView({ artifact }: { artifact: CodeArtifact }) { return <EditorSection subtitle="Three-way diff against base artifact revision." title="Effective diff"><div className="space-y-3">{artifact.diff.map((line, index) => <div className="grid overflow-hidden rounded-lg border font-mono text-[11px] md:grid-cols-2" key={index}><pre className="overflow-auto border-b bg-danger/5 p-3 text-danger-foreground md:border-b-0 md:border-r">- {line.before || "∅"}</pre><pre className="overflow-auto bg-success/5 p-3 text-success-foreground">+ {line.after}</pre></div>)}</div></EditorSection> }
function PreviewView({ artifact }: { artifact: CodeArtifact }) { return <div className="grid gap-3 lg:grid-cols-[1fr_300px]"><div className="flex min-h-[520px] items-center justify-center rounded-xl border bg-muted/30 p-6"><div className="w-full max-w-3xl rounded-xl border bg-background p-6 shadow-sm"><p className="text-[10px] uppercase tracking-[.12em] text-muted-foreground">Signed draft preview</p><h2 className="mt-2 text-xl font-semibold">Выбор гостей</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{[1, 2, 3].map((item) => <div className="aspect-[4/3] rounded-lg bg-gradient-to-br from-emerald-900 to-stone-500" key={item} />)}</div></div></div><Inspector artifact={artifact} /></div> }
function BuildView({ artifact, building, onBuild }: { artifact: CodeArtifact; building: boolean; onBuild: () => void }) { return <div className="space-y-3"><EditorSection actions={<Button disabled={building} onClick={onBuild} size="sm"><IconPlayerPlay />{building ? "Запускаем…" : "Запустить gates"}</Button>} subtitle="Ephemeral non-root, secretless, network-denied runner." title="Build gates"><div className="divide-y rounded-lg border">{artifact.gates.map((gate) => <ReleaseGateRow gate={building ? { ...gate, state: "running", detail: "Running in isolated worker…" } : gate} key={gate.id} />)}</div></EditorSection><EditorSection title="Build log"><pre className="overflow-auto rounded-lg bg-neutral-950 p-4 text-[11px] leading-5 text-neutral-200">{building ? "$ typecheck\n… running" : "$ typecheck\n✓ 0 errors\n$ lint\n✓ 0 errors\n$ build\n✓ artifact signed: sha256:8a7…\n$ a11y\n! 1 non-blocking landmark warning"}</pre></EditorSection></div> }
function Dependencies({ artifact, media }: { artifact: CodeArtifact; media: boolean }) { const items = media ? artifact.dependencies.filter((item) => item.startsWith("media:")) : artifact.dependencies; return <EditorSection title={media ? "Declared media manifest" : "Dependencies"}>{items.length ? <div className="divide-y rounded-lg border">{items.map((item) => <div className="flex min-h-12 items-center gap-2 px-3" key={item}>{media ? <IconBraces className="size-4" /> : <IconPackage className="size-4" />}<span className="font-mono text-[11px]">{item}</span><StatusBadge className="ml-auto" tone="success">Allowed</StatusBadge></div>)}</div> : <PageState icon={IconBraces} title="Media references нет">Динамические URL без asset manifest запрещены.</PageState>}</EditorSection> }
function History() { return <EditorSection title="История файла"><div className="divide-y rounded-lg border">{["Текущий черновик", "Опубликовано 28 августа", "Опубликовано 16 августа"].map((label) => <div className="flex min-h-12 items-center gap-2 px-3" key={label}><IconGitBranch className="size-4" /><span className="text-xs">{label}</span><Button className="ml-auto" onClick={() => window.alert(`Сравнение: ${label}`)} size="xs" variant="outline">Сравнить</Button></div>)}</div></EditorSection> }
