import { useCallback, useEffect, useState } from "react"
import { IconAlertTriangle, IconArchive, IconArrowLeft, IconBrandDatabricks, IconBrowser, IconCode, IconDots, IconExternalLink, IconFileAnalytics, IconGitCompare, IconHistory, IconLayoutBoard, IconLink, IconListDetails, IconPhoto, IconRocket, IconSearch, IconSettings, IconSparkles } from "@tabler/icons-react"
import { Link, useLocation, useNavigate, useParams, useSearchParams } from "react-router-dom"

import { Alert, AlertDescription, AlertTitle, Button, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, EditorFrame, EditorSection, FormField, FormSelect, Input, ListRow, ListSection, LoadingRows, PageNav, PageState, StatusBadge, Textarea, type EditorSaveState } from "@crm/ui"

import { ContentStatusBadge, InheritanceControl, PreviewDeviceSwitch, SourceMarker } from "@admin/components/cms-ui"
import { cmsRepository } from "@admin/data/cms-repository"
import { createPartnersEditorSection } from "@admin/data/partners-section"
import { PartnersSectionFields } from "@admin/components/partners-section-fields"
import { CmsConflictError, type ContentNode, type EditorRecord, type InheritanceMode } from "@admin/entities/cms"
import { useAdminAuthSession } from "@admin/features/auth-session-context"
import { useRepository } from "@admin/features/use-repository"
import { AdminApiError } from "@admin/lib/api-client"

type EditorKind = EditorRecord["kind"]
type ContentEditorTab = "content" | "composition" | "seo" | "media" | "code" | "analytics" | "versions" | "collections" | "navigation" | "media-seo"
type PublicationGate = { eligible: boolean; blockers: readonly string[] }

export type ContentEditorPageProps = {
  externalEditHref?: string
  kind: EditorKind
  nodeId?: string
  publicationGate?: PublicationGate
  returnLabel?: string
  returnTo?: string
  workspace?: "default" | "offering"
  workspaceSubjectLabel?: string
}

const commonTabs = [
  { value: "content", label: "Содержимое", compactLabel: "Контент", icon: IconListDetails }, { value: "composition", label: "Композиция", compactLabel: "Блоки", icon: IconLayoutBoard }, { value: "seo", label: "SEO", icon: IconSearch }, { value: "media", label: "Медиа", icon: IconPhoto }, { value: "code", label: "Файлы и код", compactLabel: "Код", icon: IconCode, capability: "canManageSiteCode" as const }, { value: "analytics", label: "Аналитика", compactLabel: "Метрики", icon: IconFileAnalytics, capability: "canViewAnalytics" as const }, { value: "versions", label: "История", icon: IconHistory },
]
const offeringTabs = [
  { value: "content", editorTab: "content", label: "Содержимое", compactLabel: "Контент", icon: IconListDetails },
  { value: "page-composition", editorTab: "composition", label: "Блоки страницы", compactLabel: "Блоки", icon: IconLayoutBoard },
  { value: "media", editorTab: "media", label: "Медиа", icon: IconPhoto },
  { value: "seo", editorTab: "seo", label: "SEO", icon: IconSearch },
  { value: "publication", editorTab: "versions", label: "Публикация и история", compactLabel: "Публикация", icon: IconHistory },
]

/** Canonical CMS editor. Offering dossiers pass only the located node id and host navigation. */
export function ContentEditorPage({ externalEditHref, kind, nodeId, publicationGate, returnLabel = "Закрыть", returnTo, workspace = "default", workspaceSubjectLabel = "домика" }: ContentEditorPageProps) {
  const { user } = useAdminAuthSession()
  const params = useParams(); const id = nodeId ?? (kind === "home" ? "home" : params.nodeId ?? params.entityId ?? "new")
  const loader = useCallback(() => cmsRepository.getEditor(id, kind), [id, kind]); const repositoryState = useRepository(loader)
  const topologyLoader = useCallback(() => cmsRepository.getNodes({}), []); const topologyState = useRepository(topologyLoader)
  const accessLoader = useCallback(() => cmsRepository.getAccess(), []); const accessState = useRepository(accessLoader)
  const [draft, setDraft] = useState<EditorRecord>(); const [saveState, setSaveState] = useState<EditorSaveState>("saved"); const [mutationError, setMutationError] = useState<string>(); const [publishing, setPublishing] = useState(false); const [searchParams, setSearchParams] = useSearchParams(); const navigate = useNavigate(); const location = useLocation(); const tab = searchParams.get("tab") ?? "content"; const [device, setDevice] = useState<"desktop" | "tablet" | "mobile">("desktop")
  useEffect(() => { if (repositoryState.data) { setDraft(repositoryState.data); setSaveState("saved") } }, [repositoryState.data])
  useEffect(() => {
    if (!draft || draft.id !== "new" || !topologyState.data || saveState !== "saved") return
    const requestedParentId = searchParams.get("parentNodeId")
    if (!requestedParentId) return
    const parentNode = topologyState.data.find((node) => node.id === requestedParentId)
    if (!parentNode || parentNode.status === "archived") { setMutationError("Выбранный родительский раздел не найден или архивирован."); return }
    if (draft.parentNodeId === parentNode.id) return
    setDraft(withParentPlacement(draft, parentNode.id, topologyState.data)); setSaveState("dirty")
  }, [draft, saveState, searchParams, topologyState.data])
  const hasUnsavedWork = saveState === "dirty" || saveState === "saving" || saveState === "conflict"
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (hasUnsavedWork) event.preventDefault() }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler) }, [hasUnsavedWork])
  const revisionState = draft?.revisionState ?? draft?.status
  const editable = accessState.data?.canEditContent === true && (revisionState === "draft" || revisionState === "published")
  const update = (patch: Partial<EditorRecord>) => { if (!draft || !editable) return; setDraft({ ...draft, ...patch }); setSaveState("dirty"); setMutationError(undefined) }
  const updateSection = (idToUpdate: string, mode: InheritanceMode) => { if (!draft) return; const section = draft.sections.find((item) => item.id === idToUpdate); update({ sections: draft.sections.map((item) => item.id === idToUpdate ? { ...item, mode } : item), ...(section?.label.toLocaleLowerCase("ru-RU") === "hero" ? { hero: { ...draft.hero, mode } } : {}) }) }
  const save = async () => { if (!draft || !editable) return; setSaveState("saving"); setMutationError(undefined); try { const saved = await cmsRepository.saveEditor(draft, draft.version); setDraft(saved); setSaveState("saved"); if (draft.id === "new") navigate(editorHref(saved), { replace: true }) } catch (error) { setSaveState(error instanceof CmsConflictError ? "conflict" : "dirty"); if (!(error instanceof CmsConflictError)) setMutationError(mutationMessage(error, "Не удалось сохранить")) } }
  const transition = async (action: "submit" | "return" | "approve" | "archive") => { if (!draft || draft.id === "new") return; setSaveState("saving"); setMutationError(undefined); try { let current = draft; if (action === "submit" && saveState === "dirty") current = await cmsRepository.saveEditor(current, current.version); const saved = action === "submit" ? await cmsRepository.submitReview(current.id, current.version) : action === "return" ? await cmsRepository.returnToDraft(current.id, current.version) : action === "approve" ? await cmsRepository.approve(current.id, current.version) : await cmsRepository.archive(current.id, current.version); setDraft(saved); setSaveState("saved") } catch (error) { setSaveState(error instanceof CmsConflictError ? "conflict" : action === "submit" ? "dirty" : "saved"); setMutationError(mutationMessage(error, "Операция не выполнена")) } }
  const publish = async () => { if (!draft || !accessState.data?.canPublishContent || publicationGate?.eligible === false) return; setPublishing(true); setSaveState("saving"); setMutationError(undefined); try { let current = draft; if (saveState === "dirty" || current.id === "new") current = await cmsRepository.saveEditor(current, current.version); const published = await cmsRepository.publish(current.id, current.version); setDraft(published); setSaveState("saved"); if (draft.id === "new") navigate(editorHref(published), { replace: true }) } catch (error) { setSaveState(error instanceof CmsConflictError ? "conflict" : "dirty"); setMutationError(mutationMessage(error, "Не удалось опубликовать страницу")) } finally { setPublishing(false) } }
  const back = () => { if (hasUnsavedWork && !window.confirm("Есть несохранённые изменения. Закрыть редактор?")) return; const routeState = location.state as { backTo?: unknown } | null; const routeBackTo = typeof routeState?.backTo === "string" ? routeState.backTo : kind === "category" ? "/content/categories" : kind === "profile" ? "/content/public-profiles" : kind === "home" ? "/" : "/content/pages"; navigate(returnTo ?? routeBackTo) }
  if (repositoryState.error) { const denied = repositoryState.cause instanceof AdminApiError && repositoryState.cause.isPermissionDenied; return <PageState actionLabel="Повторить" icon={IconAlertTriangle} onAction={repositoryState.reload} title={denied ? "Нет доступа к контенту" : "Редактор недоступен"}>{repositoryState.error}</PageState> }
  if (repositoryState.loading || !draft || accessState.loading || topologyState.loading) return <div className="p-4"><LoadingRows count={7} /></div>
  const allowedCommonTabs = commonTabs.filter((item) => !("capability" in item) || user.capabilities[item.capability] === true)
  const allowedOfferingTabs = offeringTabs
  const editorTabs = workspace === "offering" ? allowedOfferingTabs : kind === "home" ? [{ value: "content", label: "Секции", icon: IconLayoutBoard }, ...allowedCommonTabs.filter((item) => item.value === "composition"), { value: "collections", label: "Карточки и подборки", compactLabel: "Подборки", icon: IconSparkles }, { value: "navigation", label: "Навигация", icon: IconLink }, ...allowedCommonTabs.slice(2)] : allowedCommonTabs
  const selectedTab = editorTabs.find((item) => item.value === tab) ?? editorTabs[0]!
  const effectiveTab = ("editorTab" in selectedTab ? selectedTab.editorTab : selectedTab.value) as ContentEditorTab
  const navigation = <PageNav items={editorTabs} onValueChange={(nextTab) => { const next = new URLSearchParams(searchParams); next.set("tab", nextTab); setSearchParams(next, { replace: true }) }} value={selectedTab.value} />
  const actions = <><EditorWorkflowStatus draft={draft} /><DropdownMenu><DropdownMenuTrigger render={<Button aria-label="Ещё" size="icon-sm" variant="ghost" />}><IconDots /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem disabled>Дублировать · API operation отсутствует</DropdownMenuItem><DropdownMenuItem disabled={!accessState.data?.canEditContent || draft.id === "new" || draft.status === "archived"} onClick={() => void transition("archive")}><IconArchive />Архивировать</DropdownMenuItem></DropdownMenuContent></DropdownMenu></>
  const saveDetailProps = saveState === "conflict" ? { saveDetail: "На сервере уже есть более новые правки." } : {}
  const publishBlocked = publicationGate?.eligible === false
  const publishTitle = !accessState.data?.canPublishContent ? "Нет права публикации" : publishBlocked ? "Публикация закрыта до готовности public projection" : undefined
  return <div><div className="flex min-h-12 items-center gap-2 border-b bg-background px-3 sm:px-5 lg:px-6"><Button aria-label={returnLabel} onClick={back} size="icon-sm" variant="ghost"><IconArrowLeft /></Button><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{draft.internalName}</h2><p className="truncate text-[10px] text-muted-foreground">{draft.url} · {workspace === "offering" ? `Страница ${workspaceSubjectLabel}` : draft.status === "published" ? "на сайте" : "ещё не опубликовано"}</p></div><PreviewDeviceSwitch onChange={setDevice} value={device} /></div><EditorFrame actions={actions} footerActions={<><Button onClick={back} size="sm" variant="outline">{returnLabel}</Button><Button disabled size="sm" title="Предпросмотр подключается к render-ready API" variant="outline"><IconBrowser />Предпросмотр</Button><Button disabled={!editable || saveState === "saving" || saveState === "saved"} onClick={() => void save()} size="sm" variant="outline">Сохранить</Button>{revisionState === "draft" && draft.id !== "new" ? <Button disabled={!accessState.data?.canEditContent || saveState === "saving" || saveState === "conflict"} onClick={() => void transition("submit")} size="sm" variant="outline">{saveState === "dirty" ? "Сохранить и отправить" : "Отправить на проверку"}</Button> : null}{revisionState === "review" ? <><Button disabled={!accessState.data?.canReviewContent || saveState === "saving"} onClick={() => void transition("return")} size="sm" variant="outline">Вернуть в черновик</Button><Button disabled={!accessState.data?.canReviewContent || saveState === "saving"} onClick={() => void transition("approve")} size="sm">Одобрить</Button></> : null}<Button disabled={!accessState.data?.canPublishContent || publishBlocked || publishing || draft.status === "archived" || saveState === "conflict"} onClick={() => void publish()} size="sm" title={publishTitle}><IconRocket />{publishing ? "Публикуем…" : saveState === "dirty" ? "Сохранить и опубликовать" : "Опубликовать"}</Button></>} mobileActions={actions} navigation={navigation} {...saveDetailProps} saveState={saveState} sidebar={<EditorSidebar draft={draft} {...(externalEditHref ? { externalEditHref } : {})} location={location.pathname} />}>
    {accessState.error ? <Alert className="mb-3" variant="destructive"><IconAlertTriangle /><AlertTitle>Права не определены</AlertTitle><AlertDescription>{accessState.error}</AlertDescription></Alert> : null}{topologyState.error ? <Alert className="mb-3" variant="destructive"><IconAlertTriangle /><AlertTitle>Структура сайта недоступна</AlertTitle><AlertDescription>{topologyState.error}</AlertDescription></Alert> : null}{draft.importedFromCrm ? <Alert className="mb-3 border-info/30"><IconBrandDatabricks /><AlertTitle>Страница создана вместе с записью CRM · не опубликовано</AlertTitle><AlertDescription>Здесь оформляются тексты, блоки, медиа и SEO. Цена и условия работы остаются в CRM.</AlertDescription></Alert> : null}{publishBlocked ? <PublicationBlockedAlert blockers={publicationGate.blockers} subjectLabel={workspaceSubjectLabel} /> : null}{!editable && !accessState.error && revisionState !== "published" ? <Alert className="mb-3"><IconAlertTriangle /><AlertTitle>{revisionState === "review" ? "Материал на проверке" : revisionState === "approved" ? "Материал одобрен" : "Режим только для чтения"}</AlertTitle><AlertDescription>{revisionState === "review" ? "Проверьте материал: его можно одобрить или вернуть в черновик." : revisionState === "approved" ? "Редакция готова к публикации; для новых правок верните её в черновик." : revisionState !== "draft" ? "Запись сейчас нельзя редактировать." : "У сессии нет права редактирования."}</AlertDescription></Alert> : null}{mutationError ? <Alert className="mb-3" variant="destructive"><IconAlertTriangle /><AlertTitle>Операция не выполнена</AlertTitle><AlertDescription>{mutationError}</AlertDescription></Alert> : null}{saveState === "conflict" ? <ConflictState onReload={repositoryState.reload} /> : null}<EditorTabContent device={device} draft={draft} editable={editable} kind={kind} nodes={topologyState.data ?? []} topologyAvailable={!topologyState.error} tab={effectiveTab} update={update} updateSection={updateSection} workspace={workspace} />
  </EditorFrame></div>
}

export function EditorTabContent({ device, draft, editable, kind, nodes = [], topologyAvailable = true, tab, update, updateSection, workspace = "default" }: { device: "desktop" | "tablet" | "mobile"; draft: EditorRecord; editable: boolean; kind: EditorKind; nodes?: ContentNode[]; topologyAvailable?: boolean; tab: ContentEditorTab; update: (patch: Partial<EditorRecord>) => void; updateSection: (id: string, mode: InheritanceMode) => void; workspace?: "default" | "offering" }) {
  if (tab === "composition") return <CompositionTab draft={draft} editable={editable} updateSection={updateSection} update={update} />
  if (tab === "media-seo") return <div className="space-y-3"><SeoTab draft={draft} editable={editable} update={update} /><LinkedState title="Медиа этой страницы" detail="Галерея, alt-тексты и точки фокуса остаются в canonical media manager." href="/media" label="Открыть медиатеку" icon={IconPhoto} /></div>
  if (tab === "seo") return <SeoTab draft={draft} editable={editable} update={update} />
  if (tab === "media") return <LinkedState title="Медиа этой страницы" detail="Здесь видны изображения и файлы, а также блоки, в которых они используются." href="/media" label="Открыть медиатеку" icon={IconPhoto} />
  if (tab === "code") return <LinkedState title="Artifact ещё не привязан к странице" detail="Вкладка сохранена для controlled code workflow. До P4.8 здесь нет page → artifact API, поэтому CMS не имитирует файловое сохранение и не изменяет production checkout." href="/code" label="Открыть code workspace" icon={IconCode} />
  if (tab === "analytics") return <LinkedState title="Page analytics" detail="Stable page / section / action IDs и aggregates; без raw IP, contacts и form values." href="/analytics/content" label="Открыть отчёт" icon={IconFileAnalytics} />
  if (tab === "versions") return <VersionTab draft={draft} />
  if (tab === "collections") return <CollectionsTab />
  if (tab === "navigation") return <NavigationTab />
  return <ContentTab device={device} draft={draft} editable={editable} kind={kind} nodes={nodes} topologyAvailable={topologyAvailable} update={update} offering={workspace === "offering"} />
}

function ContentTab({ device, draft, editable, kind, nodes, topologyAvailable, update, offering = false }: { device: string; draft: EditorRecord; editable: boolean; kind: EditorKind; nodes: ContentNode[]; topologyAvailable: boolean; update: (patch: Partial<EditorRecord>) => void; offering?: boolean }) {
  if (offering) return <div className="space-y-3" data-layout="offering-dossier" data-testid="offering-dossier">
    <EditorSection subtitle="Название, адрес и краткий текст публичной страницы." title="Основное">
      <div className="grid items-start gap-3 sm:grid-cols-6"><FormField className="sm:col-span-6" htmlFor="public-title" label="Заголовок страницы"><Input id="public-title" onChange={(event) => update({ publicTitle: event.target.value })} readOnly={!editable} value={draft.publicTitle} /></FormField>{kind !== "home" ? <RoutePlacementFields compact draft={draft} editable={editable} nodes={nodes} topologyAvailable={topologyAvailable} update={update} /> : null}<FormField className="sm:col-span-6" htmlFor="description" label="Короткое описание"><Textarea id="description" onChange={(event) => update({ description: event.target.value })} readOnly={!editable} value={draft.description} /></FormField></div>
    </EditorSection>
    <div className="grid items-start gap-3 xl:grid-cols-[minmax(0,1fr)_minmax(22rem,0.9fr)]"><HeroEditor compact draft={draft} editable={editable} update={update} /><PreviewPanel device={device} draft={draft} /></div>
  </div>
  return <div className="space-y-3"><EditorSection subtitle={kind === "profile" ? "Маркетинговые поля редактируются здесь; операционные данные ниже приходят из CRM." : "Название, адрес страницы и её назначение."} title={kind === "home" ? "Главная страница" : "Основное"}><div className="grid gap-4 sm:grid-cols-2"><FormField htmlFor="internal-name" label="Внутреннее имя"><Input id="internal-name" readOnly title="Системное имя" value={draft.internalName} /></FormField><FormField htmlFor="public-title" label="Заголовок H1"><Input id="public-title" onChange={(event) => update({ publicTitle: event.target.value })} readOnly={!editable} value={draft.publicTitle} /></FormField>{kind !== "home" ? <RoutePlacementFields draft={draft} editable={editable} nodes={nodes} topologyAvailable={topologyAvailable} update={update} /> : null}<FormField className="sm:col-span-2" htmlFor="description" label="Описание и назначение"><Textarea id="description" onChange={(event) => update({ description: event.target.value })} readOnly={!editable} value={draft.description} /></FormField></div></EditorSection>
    <HeroEditor draft={draft} editable={editable} update={update} />
    {kind === "home" ? <HomeSections /> : kind === "category" ? <CategoryConfig /> : kind === "profile" ? <CrmSnapshot {...(draft.readonlyCrm ? { data: draft.readonlyCrm } : {})} /> : <LandingConfig />}
    <PreviewPanel device={device} draft={draft} />
  </div>
}

function RoutePlacementFields({ draft, editable, nodes, topologyAvailable, update, compact = false }: { draft: EditorRecord; editable: boolean; nodes: ContentNode[]; topologyAvailable: boolean; update: (patch: Partial<EditorRecord>) => void; compact?: boolean }) {
  const [parentSearch, setParentSearch] = useState("")
  const descendants = descendantIds(draft.id, nodes)
  const hasChildren = nodes.some((node) => node.parentId === draft.id)
  const moveReason = !topologyAvailable ? "Структура сайта не загружена. URL и родитель остаются без изменений." : draft.id !== "new" && draft.hasPublishedRevision ? "URL уже публикован: для переноса нужен redirect workflow." : draft.id !== "new" && hasChildren ? "У страницы есть дочерние URL: нужен atomic subtree move." : undefined
  const routeEditable = editable && !moveReason
  const search = parentSearch.trim().toLocaleLowerCase("ru-RU")
  const candidates = nodes.filter((node) => node.status !== "archived" && node.id !== draft.id && !descendants.has(node.id) && (!search || `${node.title} ${node.path}`.toLocaleLowerCase("ru-RU").includes(search)))
  const currentParent = nodes.find((node) => node.id === draft.parentNodeId)
  if (currentParent && !candidates.some((node) => node.id === currentParent.id)) candidates.unshift(currentParent)
  const changeParent = (parentNodeId: string | null) => update(withParentPlacement(draft, parentNodeId, nodes))
  const changeSlug = (slug: string) => update({ slug, url: routePath(nodes.find((node) => node.id === draft.parentNodeId)?.path, slug) })
  return <>
    <FormField className={compact ? "sm:col-span-2" : ""} htmlFor="slug" label={compact ? "Адрес страницы" : "Slug"}><Input id="slug" onChange={(event) => changeSlug(event.target.value)} readOnly={!routeEditable} value={draft.slug} /></FormField>
    <div className={compact ? "space-y-2 sm:col-span-4" : "space-y-2"}>
      <FormField htmlFor="parent-search" label="Найти родительский раздел"><Input disabled={!routeEditable} id="parent-search" onChange={(event) => setParentSearch(event.target.value)} placeholder="Название или URL" value={parentSearch} /></FormField>
      <FormField htmlFor="parent" label="Родительский раздел"><select className="h-9 w-full rounded-md border bg-background px-3 text-xs disabled:cursor-not-allowed disabled:opacity-50" disabled={!routeEditable} id="parent" onChange={(event) => changeParent(event.target.value || null)} value={draft.parentNodeId ?? ""}><option value="">Корень сайта</option>{candidates.map((node) => <option key={node.id} value={node.id}>{node.title} · {node.path}</option>)}</select></FormField>
    </div>
    <Alert className={`${compact ? "sm:col-span-6" : "sm:col-span-2"} ${moveReason ? "border-warning/35" : "border-info/25"}`}><IconLink /><AlertTitle>{moveReason ? "Перенос сейчас недоступен" : "Адрес страницы"}</AlertTitle><AlertDescription>{moveReason ?? <span className="font-mono">{draft.url}</span>}</AlertDescription></Alert>
  </>
}

function HeroEditor({ draft, editable, update, compact = false }: { draft: EditorRecord; editable: boolean; update: (patch: Partial<EditorRecord>) => void; compact?: boolean }) {
  const change = <K extends keyof EditorRecord["hero"]>(key: K, value: EditorRecord["hero"][K]) => update({ hero: { ...draft.hero, [key]: value } })
  const own = draft.hero.mode === "override"
  const modeOptions = [{ value: "inherit", label: "Общие настройки" }, { value: "override", label: "Настроить здесь" }, { value: "disabled", label: "Скрыть первый экран" }]
  return <EditorSection subtitle={compact ? "Первый экран публичной страницы: текст, кнопки и фото." : "Шаблон этой страницы. Можно унаследовать общий hero, заменить любые элементы или полностью скрыть."} title={compact ? "Первый экран" : "Hero этой страницы"}>
    <div className="grid gap-3">
      <FormSelect disabled={!editable} id="hero-mode" label={compact ? "Вариант первого экрана" : "Как показывать"} onValueChange={(value) => change("mode", value as InheritanceMode)} options={compact ? modeOptions : [{ value: "inherit", label: "Как на сайте по умолчанию" }, { value: "override", label: "Настроить для этой страницы" }, { value: "disabled", label: "Не показывать" }]} value={draft.hero.mode} />
      {draft.hero.mode === "disabled" ? <Alert className="border-warning/30"><IconAlertTriangle /><AlertTitle>{compact ? "Первый экран скрыт" : "Hero скрыт на этой странице"}</AlertTitle><AlertDescription>Проверьте, что заголовок страницы и основной призыв к действию остаются доступны в другом блоке.</AlertDescription></Alert> : null}
      {own ? <><div className={compact ? "grid gap-3 sm:grid-cols-6" : "grid gap-4 sm:grid-cols-2"}><FormField className={compact ? "sm:col-span-2" : ""} htmlFor="hero-eyebrow" label="Надпись над заголовком"><Input id="hero-eyebrow" onChange={(event) => change("eyebrow", event.target.value)} readOnly={!editable} value={draft.hero.eyebrow} /></FormField><FormField className={compact ? "sm:col-span-4" : ""} htmlFor="hero-title" label={compact ? "Заголовок первого экрана" : "Заголовок hero"}><Input id="hero-title" onChange={(event) => change("title", event.target.value)} readOnly={!editable} value={draft.hero.title} /></FormField><FormField className="sm:col-span-6" htmlFor="hero-description" label="Текст"><Textarea id="hero-description" onChange={(event) => change("description", event.target.value)} readOnly={!editable} value={draft.hero.description} /></FormField></div>
        <div className="grid gap-4 sm:grid-cols-2"><FormField htmlFor="hero-primary-label" label="Основная кнопка · текст"><Input id="hero-primary-label" onChange={(event) => change("primaryCtaLabel", event.target.value)} readOnly={!editable} value={draft.hero.primaryCtaLabel} /></FormField><FormField htmlFor="hero-primary-target" label="Основная кнопка · ссылка"><Input id="hero-primary-target" onChange={(event) => change("primaryCtaTarget", event.target.value)} readOnly={!editable} value={draft.hero.primaryCtaTarget} /></FormField><FormField htmlFor="hero-secondary-label" label="Вторая кнопка · текст"><Input id="hero-secondary-label" onChange={(event) => change("secondaryCtaLabel", event.target.value)} readOnly={!editable} value={draft.hero.secondaryCtaLabel} /></FormField><FormField htmlFor="hero-secondary-target" label="Вторая кнопка · ссылка"><Input id="hero-secondary-target" onChange={(event) => change("secondaryCtaTarget", event.target.value)} readOnly={!editable} value={draft.hero.secondaryCtaTarget} /></FormField></div>
        <div className="grid gap-4 sm:grid-cols-2"><FormField htmlFor="hero-desktop-image" label="Фоновое изображение"><Input id="hero-desktop-image" onChange={(event) => change("desktopImage", event.target.value)} placeholder="Выберите в медиа или вставьте путь" readOnly={!editable} value={draft.hero.desktopImage} /></FormField><FormField htmlFor="hero-mobile-image" label="Изображение для телефона"><Input id="hero-mobile-image" onChange={(event) => change("mobileImage", event.target.value)} placeholder="Необязательно" readOnly={!editable} value={draft.hero.mobileImage} /></FormField><FormField htmlFor="hero-overlay" label="Затемнение фона, %"><Input id="hero-overlay" max={90} min={0} onChange={(event) => change("overlay", Math.max(0, Math.min(90, Number(event.target.value))))} readOnly={!editable} type="number" value={draft.hero.overlay} /></FormField><FormSelect disabled={!editable} id="hero-focal" label="Фокус изображения" onValueChange={(value) => change("focalPosition", value as EditorRecord["hero"]["focalPosition"])} options={[{ value: "left", label: "Слева" }, { value: "center", label: "По центру" }, { value: "right", label: "Справа" }]} value={draft.hero.focalPosition} /><FormSelect disabled={!editable} id="hero-alignment" label="Выравнивание текста" onValueChange={(value) => change("alignment", value as EditorRecord["hero"]["alignment"])} options={[{ value: "left", label: "Слева" }, { value: "center", label: "По центру" }]} value={draft.hero.alignment} /><div className="flex items-end"><Button className="w-full" onClick={() => window.location.assign("/media")} type="button" variant="outline"><IconPhoto />Открыть медиатеку</Button></div></div></> : draft.hero.mode === "inherit" ? <div className="rounded-lg border bg-muted/25 p-3"><p className="text-xs font-medium">Используются общие настройки hero</p><p className="mt-1 text-[10px] text-muted-foreground">Чтобы заменить текст, кнопки или изображения только здесь, выберите «Настроить для этой страницы».</p></div> : null}
    </div>
  </EditorSection>
}

function CompositionTab({ draft, editable, updateSection, update }: { draft: EditorRecord; editable: boolean; updateSection: (id: string, mode: InheritanceMode) => void; update: (patch: Partial<EditorRecord>) => void }) {
  return <EditorSection subtitle="site default → page type → parent/category → page/profile" title="Наследуемые секции"><div className="space-y-3">{draft.sections.map((section) => <div key={section.id}>
    <InheritanceControl disabled={!editable || (section.key === "partners" && !section.partnersConfig)} onChange={(mode) => updateSection(section.id, mode)} section={section} />
    {section.mode === "override" && section.partnersConfig && <PartnersSectionFields id={section.id} value={section.partnersConfig} editable={editable} onChange={(partnersConfig) => update({ sections: draft.sections.map((current) => current.id === section.id ? { ...current, partnersConfig } : current) })} />}
    {section.key === "partners" && !section.partnersConfig && <p className="mt-2 text-xs text-muted-foreground">Редактор этой версии или составной конфигурации пока недоступен. Сохранение остальных полей не изменяет её содержимое.</p>}
  </div>)}
  {draft.kind === "home" && !draft.sections.some((section) => section.key === "partners") && <Button disabled={!editable} onClick={() => update({ sections: [...draft.sections, createPartnersEditorSection()] })} size="sm" variant="outline">Добавить секцию «Партнёры»</Button>}
  </div></EditorSection>
}

function SeoTab({ draft, editable, update }: { draft: EditorRecord; editable: boolean; update: (patch: Partial<EditorRecord>) => void }) { return <div className="space-y-3"><Alert className={draft.seoChecks.blockers ? "border-danger/30" : "border-success/30"}><IconSearch /><AlertTitle>{draft.seoChecks.passed} checks passed · {draft.seoChecks.warnings} warning · {draft.seoChecks.blockers} blocker</AlertTitle><AlertDescription>Оценка собрана из явных правил, а не из магического score.</AlertDescription></Alert><EditorSection title="Metadata"><div className="grid gap-4"><FormField htmlFor="seo-title" label="SEO title"><Input id="seo-title" onChange={(event) => update({ seoTitle: event.target.value })} readOnly={!editable} value={draft.seoTitle} /></FormField><FormField htmlFor="seo-description" label="SEO description"><Textarea id="seo-description" onChange={(event) => update({ seoDescription: event.target.value })} readOnly={!editable} value={draft.seoDescription} /></FormField><FormField htmlFor="canonical" label="Canonical"><Input id="canonical" readOnly value={`https://svistoplyasovo.ru${draft.url}`} /></FormField><FormField htmlFor="indexing" label="Indexing"><Input id="indexing" readOnly value={draft.indexPolicy} /></FormField></div></EditorSection><EditorSection subtitle="Как результат может выглядеть в поиске" title="Snippet preview"><div className="max-w-2xl rounded-lg border p-4"><p className="text-base text-[#1a0dab]">{draft.seoTitle}</p><p className="mt-1 text-xs text-[#006621]">svistoplyasovo.ru{draft.url}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{draft.seoDescription}</p></div></EditorSection></div> }

function EditorSidebar({ draft, externalEditHref, location }: { draft: EditorRecord; externalEditHref?: string; location: string }) { return <div className="space-y-3"><section className="overflow-hidden rounded-xl border bg-background"><ListSection count={5} icon={IconSettings} title="Страница"><ListRow><Summary label="Статус" value={<EditorWorkflowStatus draft={draft} />} /></ListRow><ListRow><Summary label="URL" value={<span className="font-mono">{draft.url}</span>} /></ListRow><ListRow><Summary label="Ответственный" value={draft.owner} /></ListRow><ListRow><Summary label="Обновлено" value={draft.updatedLabel} /></ListRow><ListRow><Summary label="Публикация" value={draft.reviewLabel} /></ListRow></ListSection></section><section className="rounded-xl border bg-background p-4"><h3 className="text-[13px] font-semibold">Готовность страницы</h3><div className="mt-3 grid grid-cols-3 divide-x text-center"><Quality value={draft.seoChecks.passed} label="Готово" tone="success" /><Quality value={draft.seoChecks.warnings} label="Проверить" tone="warning" /><Quality value={draft.seoChecks.blockers} label="Исправить" tone="danger" /></div><Link className="mt-3 flex items-center justify-center gap-1 rounded-md border px-2 py-2 text-xs hover:bg-muted" to={`/seo/pages/${draft.id}?return=${encodeURIComponent(location)}`}><IconSearch className="size-4" />SEO-отчёт</Link></section>{externalEditHref ? <a className="flex items-center gap-2 rounded-xl border bg-info-subtle p-3 text-xs font-medium text-info-foreground hover:brightness-95" href={externalEditHref}><IconBrandDatabricks className="size-4" />Цена и работа ресурса — в CRM<IconExternalLink className="ml-auto size-3" /></a> : null}</div> }
function EditorWorkflowStatus({ draft }: { draft: EditorRecord }) { return draft.revisionState === "approved" ? <StatusBadge tone="info">Одобрено</StatusBadge> : <ContentStatusBadge status={draft.status} /> }

function Summary({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex min-h-11 items-center justify-between gap-3 px-4 py-2"><span className="text-[10px] text-muted-foreground">{label}</span><span className="min-w-0 truncate text-right text-xs font-medium">{value}</span></div> }
function Quality({ label, tone, value }: { label: string; tone: string; value: number }) { return <div><p className={`text-lg font-semibold text-${tone}`}>{value}</p><p className="text-[9px] text-muted-foreground">{label}</p></div> }

function ConflictState({ onReload }: { onReload: () => void }) { return <Alert className="mb-3 border-danger/30" variant="destructive"><IconGitCompare /><AlertTitle>Страница уже изменена в другой вкладке</AlertTitle><AlertDescription><p>Обновите данные перед сохранением, чтобы не затереть чужие правки. Сайт не изменился.</p><div className="mt-2 flex gap-2"><Button onClick={onReload} size="xs" variant="outline">Обновить</Button></div></AlertDescription></Alert> }

const publicationBlockerLabels: Record<string, string> = {
  cms_node_archived: "Материал в архиве",
  cms_node_kind_incompatible: "Тип страницы не совместим с этой записью",
  offering_not_active: "Рабочая запись ещё не активна",
  public_profile_mismatch: "Публичный профиль связан с другой редакцией",
  public_profile_missing: "Показ на сайте не настроен",
  revision_relation_mismatch: "Связь редакции не совпадает",
  revision_relation_missing: "Редакция не связана с рабочей записью",
  safe_public_projection_missing: "Данные для сайта ещё не подготовлены",
}

function PublicationBlockedAlert({ blockers, subjectLabel }: { blockers: readonly string[]; subjectLabel: string }) {
  return <Alert className="mb-3 border-warning/35"><IconAlertTriangle /><AlertTitle>Публикация {subjectLabel} закрыта</AlertTitle><AlertDescription><p>Черновик можно редактировать и проверять, но сайт не изменится, пока не готовы цена, страница и безопасная публикация.</p><ul className="mt-2 list-disc space-y-1 pl-4">{blockers.map((blocker) => <li key={blocker}>{publicationBlockerLabels[blocker] ?? blocker}</li>)}</ul></AlertDescription></Alert>
}

function HomeSections() { const demo = cmsRepository.mode === "api"; return <EditorSection actions={<Button disabled={demo} onClick={() => window.alert("Секция добавлена в fixture outline") } size="xs" title={demo ? "Section outline API ещё не реализован" : undefined} variant="outline">+Добавить</Button>} subtitle="Порядок, visibility, source и mobile behavior" title="Секции главной">{demo ? <PrototypeNotice feature="Расширенный outline главной" /> : null}<div className="divide-y rounded-lg border">{["События", "Домики", "Баня и чан", "Программы", "Площадки", "Блог", "Why us", "Отзывы"].map((label, index) => <div className="flex min-h-12 items-center gap-3 px-3" key={label}><span className={demo ? "text-muted-foreground" : "cursor-grab text-muted-foreground"}>⋮⋮</span><span className="min-w-0 flex-1 text-xs font-medium">{label}</span><SourceMarker source={index < 5 ? "CRM" : "CMS"} /><StatusBadge tone={demo ? "neutral" : "success"}>{demo ? "Demo" : "Видимо"}</StatusBadge></div>)}</div></EditorSection> }
function LandingConfig() { const [mode, setMode] = useState("composition"); const [direction, setDirection] = useState("stay"); const demo = cmsRepository.mode === "api"; return <EditorSection subtitle="Indexable landing требует unique intent, canonical, internal links и review date." title="Поисковое назначение">{demo ? <PrototypeNotice feature="Intent, audience и lead direction" /> : null}<div className="grid gap-4 sm:grid-cols-2"><FormField htmlFor="intent" label="Intent / topic"><Input defaultValue="Семейный отдых в Нижегородской области" id="intent" readOnly={demo} /></FormField><FormField htmlFor="audience" label="Audience note"><Input defaultValue="Семьи с детьми 4–12 лет" id="audience" readOnly={demo} /></FormField><FormSelect disabled={demo} id="mode" label="Page mode" onValueChange={setMode} options={[{ value: "composition", label: "Composition" }, { value: "template", label: "Template" }, { value: "code", label: "Controlled custom code" }]} value={mode} /><FormSelect disabled={demo} id="cta" label="Lead direction" onValueChange={setDirection} options={[{ value: "stay", label: "Проживание" }, { value: "program", label: "Программа" }]} value={direction} /></div></EditorSection> }
function CategoryConfig() { const demo = cmsRepository.mode === "api"; return <EditorSection subtitle="Faceted URLs noindex по умолчанию; indexable combinations создаются как curated pages." title="Источник и фильтры"><div className="grid gap-3">{demo ? <PrototypeNotice feature="Category filters и indexability rules" /> : <Alert className="border-warning/25"><IconAlertTriangle /><AlertTitle>24 потенциальных URL</AlertTitle><AlertDescription>0 indexable combinations. Массовая индексация заблокирована quality policy.</AlertDescription></Alert>}{[["Вместимость", "guests", "Number range"], ["Особенности", "features", "Multi-select"], ["Доступность", "available", "Date-aware"]].map(([label, key, type]) => <div className="grid grid-cols-[1fr_100px_100px] items-center gap-2 rounded-lg border px-3 py-2" key={key}><span className="text-xs font-medium">{label}<span className="block text-[10px] text-muted-foreground">URL key: {key}</span></span><StatusBadge tone={demo ? "neutral" : "info"}>{demo ? "Demo" : type}</StatusBadge><StatusBadge tone="neutral">noindex</StatusBadge></div>)}</div></EditorSection> }
function CrmSnapshot({ data }: { data?: NonNullable<EditorRecord["readonlyCrm"]> }) { if (!data) return null; return <EditorSection actions={<SourceMarker source="CRM" />} subtitle="Authoritative values не дублируются в CMS." title="Данные CRM · readonly"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(data).map(([key, value]) => <div className="rounded-lg border bg-muted/25 p-3" key={key}><p className="text-[10px] text-muted-foreground">{key}</p><p className="mt-1 text-xs font-medium">{value}</p></div>)}</div></EditorSection> }
function PreviewPanel({ device, draft }: { device: string; draft: EditorRecord }) { const api = cmsRepository.mode === "api"; const own = draft.hero.mode === "override"; const title = own ? draft.hero.title : draft.publicTitle; const description = own ? draft.hero.description : draft.description; const image = device === "mobile" && draft.hero.mobileImage ? draft.hero.mobileImage : draft.hero.desktopImage; return <EditorSection actions={<StatusBadge tone="info">{device === "mobile" ? "Телефон" : device === "tablet" ? "Планшет" : "Компьютер"}</StatusBadge>} subtitle={api ? "Предварительный вид по сохранённым настройкам страницы." : "Предварительный вид черновика до публикации."} title="Как выглядит hero">{draft.hero.mode === "disabled" ? <PageState icon={IconPhoto} title="Hero скрыт">На этой странице первым будет следующий включённый блок.</PageState> : <div className={`mx-auto overflow-hidden rounded-lg border bg-neutral-900 text-white transition-all ${device === "mobile" ? "max-w-[360px]" : device === "tablet" ? "max-w-[720px]" : "max-w-none"}`}><div className={`relative flex min-h-64 flex-col justify-end overflow-hidden p-6 ${draft.hero.alignment === "center" ? "items-center text-center" : "items-start text-left"}`} style={{ backgroundColor: "#24372d", backgroundImage: image ? `url(${image})` : "linear-gradient(135deg,#173f2c,#3c3934)", backgroundPosition: draft.hero.focalPosition, backgroundSize: "cover" }}><span className="absolute inset-0 bg-black" style={{ opacity: draft.hero.overlay / 100 }} /><div className="relative z-10"><p className="text-[10px] uppercase tracking-[.15em] text-white/70">{own ? draft.hero.eyebrow : "Свистоплясово"}</p><h3 className="mt-2 max-w-xl text-2xl font-semibold">{title}</h3><p className="mt-2 max-w-lg text-xs leading-5 text-white/75">{description}</p><div className={`mt-4 flex flex-wrap gap-2 ${draft.hero.alignment === "center" ? "justify-center" : "justify-start"}`}><Button disabled={api} size="sm" title={api ? "Интерактивный предпросмотр подключается отдельно" : undefined}>{draft.hero.primaryCtaLabel || "Подобрать отдых"}</Button>{own && draft.hero.secondaryCtaLabel ? <Button className="border-white/35 bg-white/10 text-white" disabled={api} size="sm" variant="outline">{draft.hero.secondaryCtaLabel}</Button> : null}</div></div></div></div>}</EditorSection> }
function CollectionsTab() { const demo = cmsRepository.mode === "api"; return <EditorSection subtitle="CRM query, manual, computed; availability и price остаются authoritative в public API." title="Карточки и подборки">{demo ? <PrototypeNotice feature="Collection bindings" /> : null}<div className="divide-y rounded-lg border">{["Домики · CRM query · capacity desc · limit 6", "Программы · manual pins + fallback · limit 4", "Блог · computed: featured · limit 4"].map((label) => <div className="flex min-h-14 items-center px-3 text-xs" key={label}>{label}<Button className="ml-auto" disabled={demo} onClick={() => window.alert(`${label}: открыта локальная fixture-настройка`)} size="xs" title={demo ? "Collections API ещё не реализован" : undefined} variant="outline">Настроить</Button></div>)}</div></EditorSection> }
function NavigationTab() { const demo = cmsRepository.mode === "api"; return <EditorSection subtitle="Anchors, menu labels, mobile order и CTA." title="Навигация главной">{demo ? <PrototypeNotice feature="Home navigation anchors" /> : null}<div className="grid gap-3 sm:grid-cols-2"><FormField htmlFor="anchor-houses" label="Домики"><Input defaultValue="#houses" id="anchor-houses" readOnly={demo} /></FormField><FormField htmlFor="anchor-programs" label="Программы"><Input defaultValue="#programs" id="anchor-programs" readOnly={demo} /></FormField></div></EditorSection> }
function VersionTab({ draft }: { draft: EditorRecord }) { if (cmsRepository.mode === "api") return <EditorSection title="История"><PageState icon={IconHistory} title="История правок">Сейчас видна текущая сохранённая версия. Подробное сравнение правок будет добавлено без отдельного сценария публикации.</PageState></EditorSection>; return <EditorSection subtitle="Предыдущие варианты страницы доступны для сравнения и восстановления." title="История правок"><div className="divide-y rounded-lg border">{[draft.version, draft.version - 1, draft.version - 2].map((version, index) => <div className="flex min-h-14 items-center gap-3 px-3" key={version}><IconHistory className="size-4 text-muted-foreground" /><span className="min-w-0 flex-1 text-xs"><strong>{index === 0 ? "Текущая версия" : `Версия ${version}`}</strong><span className="block text-[10px] text-muted-foreground">{index === 0 ? "Последние сохранённые правки" : "Ранее была на сайте"}</span></span><Button disabled={index === 0} size="xs" title={index === 0 ? "Текущая версия" : undefined} variant="outline">Сравнить</Button></div>)}</div></EditorSection> }
function LinkedState({ detail, href, icon, label, title }: { detail: string; href: string; icon: React.ElementType; label: string; title: string }) { return <EditorSection title={title}><PageState actionLabel={label} icon={icon} onAction={() => window.location.assign(href)} title={title}>{detail}</PageState></EditorSection> }
function editorHref(record: EditorRecord) { return record.kind === "home" ? "/content/home" : record.kind === "category" ? `/content/categories/${record.id}` : record.kind === "profile" ? `/content/public-profiles/resource/${record.id}` : record.kind === "article" ? `/content/articles/${record.id}` : `/content/pages/${record.id}` }
function routePath(parentPath: string | undefined, slug: string) { const cleanSlug = slug.replace(/^\/+|\/+$/g, ""); const base = parentPath && parentPath !== "/" ? parentPath.replace(/\/$/, "") : ""; return `${base}/${cleanSlug}` }
function descendantIds(nodeId: string, nodes: ContentNode[]) { const result = new Set<string>(); if (nodeId === "new") return result; const queue = [nodeId]; while (queue.length) { const parentId = queue.shift()!; for (const node of nodes) if (node.parentId === parentId && !result.has(node.id)) { result.add(node.id); queue.push(node.id) } } return result }
function withParentPlacement(draft: EditorRecord, parentNodeId: string | null, nodes: ContentNode[]): EditorRecord { const parent = nodes.find((node) => node.id === parentNodeId); const siblingOrders = nodes.filter((node) => node.id !== draft.id && node.parentId === parentNodeId).map((node) => node.sortOrder); const sortOrder = draft.parentNodeId === parentNodeId && draft.sortOrder !== undefined ? draft.sortOrder : Math.min(100000, (siblingOrders.length ? Math.max(...siblingOrders) : 0) + 10); return { ...draft, parentNodeId, parent: parent?.title ?? "Корень сайта", sortOrder, url: routePath(parent?.path, draft.slug) } }
function mutationMessage(error: unknown, fallback: string) { if (!(error instanceof Error)) return fallback; if (!(error instanceof AdminApiError)) return error.message; const topologyLabels: Record<string, string> = { CMS_PARENT_INVALID: "Родительский раздел недоступен. Выберите другой активный раздел.", CMS_PARENT_CYCLE: "Этот родитель создаст цикл в дереве. Выберите другой раздел.", CMS_ROUTE_INVALID: "URL не соответствует выбранному родителю и slug.", CMS_SUBTREE_MOVE_REQUIRED: "У страницы есть дочерние URL. Для переноса нужен atomic subtree move.", CMS_REDIRECT_REQUIRED: "URL уже был опубликован. Создайте redirect proposal перед переносом." }; const fields = Object.entries(error.fieldErrors ?? {}).flatMap(([field, messages]) => messages.map((message) => `${field}: ${message}`)); return [topologyLabels[error.rawCode ?? ""] ?? error.message, ...fields, ...(error.requestId ? [`Request ID: ${error.requestId}`] : [])].join(" · ") }
function PrototypeNotice({ feature }: { feature: string }) { return <Alert className="mb-3 border-warning/30"><IconAlertTriangle /><AlertTitle>{feature}: demo</AlertTitle><AlertDescription>Поля показывают целевой UX, но не сохраняются: authoritative API для этого блока ещё не реализован.</AlertDescription></Alert> }
