import { IconAlertTriangle, IconArrowRight, IconComponents, IconHistory, IconNavigation, IconPlus, IconReportSearch, IconRoute, IconSettings, IconSparkles, IconTemplate, IconUsers, IconWorldCog } from "@tabler/icons-react"
import { Link, useLocation } from "react-router-dom"

import { Alert, AlertDescription, AlertTitle, Button, EditorSection, IconBox, PageFrame, StatusBadge } from "@crm/ui"

import { PageHeading, SourceMarker } from "@admin/components/cms-ui"
import { cmsRepository } from "@admin/data/cms-repository"

const pages: Record<string, { title: string; description: string; icon: React.ElementType; items: { title: string; detail: string; status: string; tone: "success" | "warning" | "neutral" | "info"; href?: string }[] }> = {
  "/globals/sections": { title: "Глобальные секции", description: "Versioned presets, variants, usage count и blast radius для inherited slots.", icon: IconTemplate, items: [{ title: "Hero · по умолчанию", detail: "42 routes · 6 local overrides · revision 18", status: "Published", tone: "success" }, { title: "Карта базы", detail: "18 routes · revision 3", status: "Published", tone: "success" }, { title: "FAQ и как добраться", detail: "36 routes · schema eligible", status: "Warning", tone: "warning" }, { title: "Калькулятор", detail: "Public API preset · 22 routes", status: "Published", tone: "success" }] },
  "/globals/navigation": { title: "Навигация и footer", description: "Единый link registry для desktop/mobile header и footer; broken-link validation.", icon: IconNavigation, items: [{ title: "Desktop header", detail: "3 levels · 18 links · CTA «Забронировать»", status: "Valid", tone: "success" }, { title: "Mobile menu", detail: "12 links · independent order", status: "Valid", tone: "success" }, { title: "Footer", detail: "Contacts from CRM · legal from CMS", status: "1 warning", tone: "warning", href: "/globals/footer" }] },
  "/components": { title: "Компоненты и шаблоны", description: "Block registry с schema/renderer versions. Unknown renderer нельзя создать из JSON.", icon: IconComponents, items: [{ title: "public.hero", detail: "schema v3 · renderer 2.8.0 · 42 usages", status: "Stable", tone: "success" }, { title: "public.cardRail", detail: "schema v2 · renderer 2.4.1 · 16 usages", status: "Stable", tone: "success" }, { title: "public.calculator", detail: "island · schema v4 · public API", status: "Controlled", tone: "info" }] },
  "/seo": { title: "SEO", description: "Rule-based report: indexing, metadata, schema, links, images, sitemap/robots, redirects и freshness.", icon: IconReportSearch, items: [{ title: "Indexable pages", detail: "42 production · 0 accidental faceted URLs", status: "OK", tone: "success" }, { title: "Metadata", detail: "2 long titles · 1 missing description", status: "3 warnings", tone: "warning" }, { title: "Internal links", detail: "3 orphan drafts", status: "Review", tone: "warning" }, { title: "Schema", detail: "39 valid · 3 not eligible", status: "OK", tone: "success" }] },
  "/marketing/campaigns": { title: "Маркетинг и кампании", description: "UTM allowlist, landing/CTA bindings и display content. Скидка не вычисляется в CMS.", icon: IconSparkles, items: [{ title: "Бархатный сезон", detail: "utm_campaign=velvet_2026 · /family", status: "Active", tone: "success" }, { title: "Новый год", detail: "Starts 01 ноя · content only", status: "Draft", tone: "neutral" }] },
  "/redirects": { title: "Редиректы", description: "Revision-scoped redirect registry, chains/loops validation и automatic proposal при slug changes.", icon: IconRoute, items: [{ title: "/domiki → /houses", detail: "301 · legacy migration", status: "Active", tone: "success" }, { title: "/family-rest → /family", detail: "301 · proposed by slug change", status: "Draft", tone: "warning" }] },
  "/settings/site": { title: "Настройки сайта", description: "Site defaults, domains, contacts projection, default slots и environment policy.", icon: IconSettings, items: [{ title: "Production domain", detail: "svistoplyasovo.ru · HTTPS", status: "Verified", tone: "success" }, { title: "Default inheritance", detail: "Hero, map, FAQ, directions, calculator, footer", status: "Configured", tone: "success" }] },
  "/settings/integrations": { title: "Интеграции", description: "Сайт ↔ public API ↔ CMS/CRM, cache delivery, search services и consent-gated analytics.", icon: IconWorldCog, items: [{ title: "Public API", detail: "/api/public/v1 · separate OpenAPI", status: "Planned P4.2", tone: "info" }, { title: "Яндек.Метрика", detail: "Consent gate и legal owner требуют approval", status: "Blocked", tone: "warning" }, { title: "CDN revalidation", detail: "Provider selection required in P4.0", status: "Decision needed", tone: "warning" }] },
  "/settings/access": { title: "Пользователи и права", description: "Capabilities разделяют content, SEO, media, publish, code, integrations и raw analytics access.", icon: IconUsers, items: [{ title: "Издатель", detail: "view/edit/publish content · manage media/SEO", status: "3 users", tone: "info" }, { title: "Редактор", detail: "view/edit content · request review", status: "5 users", tone: "info" }, { title: "Technical admin", detail: "manage site code · no self-approval", status: "1 user", tone: "warning" }] },
  "/audit": { title: "Журнал изменений", description: "Кто, когда и что изменил. История доступна только пользователям с соответствующим правом.", icon: IconHistory, items: [{ title: "Марина К. обновила hero", detail: "Главная · заголовок · 12 мин назад", status: "Сохранено", tone: "success" }, { title: "Олег М. изменил посадочную", detail: "Отдых с детьми · 34 мин назад", status: "Черновик", tone: "warning" }, { title: "Не обработано изображение", detail: "bath-gallery.tiff · формат не поддерживается", status: "Ошибка", tone: "warning" }] },
}

export function ManagementPage({ mode }: { mode?: "footer" | "component" | "seo-page" }) {
  const location = useLocation(); const key = mode === "footer" ? "/globals/navigation" : mode === "component" ? "/components" : mode === "seo-page" ? "/seo" : location.pathname; const data = pages[key] ?? pages["/settings/site"]!
  const demo = cmsRepository.mode === "api"
  return <PageFrame><PageHeading actions={<Button disabled={demo} onClick={() => window.alert("Действие создаст draft за repository boundary") } size="sm" title={demo ? "Для этого раздела authoritative API ещё не реализован" : undefined}><IconPlus />Создать</Button>} description={data.description} title={mode === "footer" ? "Footer" : mode === "seo-page" ? "SEO-отчёт страницы" : data.title} />{demo ? <Alert className="mb-3 border-warning/30"><IconAlertTriangle /><AlertTitle>Демонстрационная спецификация</AlertTitle><AlertDescription>Карточки ниже показывают запланированную структуру и состояния, а не серверные данные. Изменения отключены до появления authoritative API этого раздела.</AlertDescription></Alert> : null}<div className="space-y-2">{data.items.map((item) => <div className="flex min-h-16 items-center gap-3 rounded-xl border bg-background px-4 py-3" key={item.title}><IconBox icon={data.icon} size="sm" variant={item.tone === "warning" ? "warning" : item.tone === "success" ? "success" : "info"} /><div className="min-w-0 flex-1"><p className="text-xs font-medium">{item.title}</p><p className="mt-0.5 truncate text-[10px] text-muted-foreground">{item.detail}</p></div>{key === "/settings/integrations" ? <SourceMarker source="computed" /> : null}{demo ? <StatusBadge tone="neutral">Demo</StatusBadge> : <StatusBadge tone={item.tone}>{item.status}</StatusBadge>}{item.href && !demo ? <Link className="text-primary" to={item.href}><IconArrowRight className="size-4" /></Link> : <Button aria-label={`Открыть ${item.title}`} disabled={demo} onClick={() => window.alert(`${item.title}: editor подключится к admin API в следующем этапе`) } size="icon-xs" title={demo ? "Backend API ещё не реализован" : undefined} variant="ghost"><IconArrowRight /></Button>}</div>)}</div>{mode === "seo-page" ? <EditorSection className="mt-3" title="Canonical editor boundary"><p className="text-xs text-muted-foreground">SEO-отчёт только диагностирует. Поля SEO редактируются в canonical content editor, поэтому второго authority здесь нет.</p><Button className="mt-3" disabled={demo} onClick={() => window.location.assign("/content/pages/landing-family?tab=seo") } size="sm" title={demo ? "SEO report API ещё не реализован" : undefined} variant="outline"><IconReportSearch />Редактировать SEO в странице</Button></EditorSection> : null}</PageFrame>
}
