import { IconAlertTriangle, IconArrowRight, IconComponents, IconHistory, IconNavigation, IconPlus, IconWorldCog } from "@tabler/icons-react"
import { Link, useLocation } from "react-router-dom"

import { Alert, AlertDescription, AlertTitle, Button, IconBox, PageFrame, StatusBadge } from "@crm/ui"

import { PageHeading, SourceMarker } from "@admin/components/cms-ui"
import { cmsRepository } from "@admin/data/cms-repository"

const pages: Record<string, { title: string; description: string; icon: React.ElementType; items: { title: string; detail: string; status: string; tone: "success" | "warning" | "neutral" | "info"; href?: string }[] }> = {
  "/globals/navigation": { title: "Навигация и footer", description: "Единый link registry для desktop/mobile header и footer; broken-link validation.", icon: IconNavigation, items: [{ title: "Desktop header", detail: "3 levels · 18 links · CTA «Забронировать»", status: "Valid", tone: "success" }, { title: "Mobile menu", detail: "12 links · independent order", status: "Valid", tone: "success" }, { title: "Footer", detail: "Contacts from CRM · legal from CMS", status: "1 warning", tone: "warning", href: "/globals/footer" }] },
  "/components": { title: "Компоненты и шаблоны", description: "Block registry с schema/renderer versions. Unknown renderer нельзя создать из JSON.", icon: IconComponents, items: [{ title: "public.hero", detail: "schema v3 · renderer 2.8.0 · 42 usages", status: "Stable", tone: "success" }, { title: "public.cardRail", detail: "schema v2 · renderer 2.4.1 · 16 usages", status: "Stable", tone: "success" }, { title: "public.calculator", detail: "island · schema v4 · public API", status: "Controlled", tone: "info" }] },
  "/settings/integrations": { title: "Интеграции", description: "Сайт ↔ public API ↔ CMS/CRM, cache delivery, search services и consent-gated analytics.", icon: IconWorldCog, items: [{ title: "Public API", detail: "/api/public/v1 · separate OpenAPI", status: "Planned P4.2", tone: "info" }, { title: "Яндек.Метрика", detail: "Consent gate и legal owner требуют approval", status: "Blocked", tone: "warning" }, { title: "CDN revalidation", detail: "Provider selection required in P4.0", status: "Decision needed", tone: "warning" }] },
  "/audit": { title: "Журнал изменений", description: "Кто, когда и что изменил. История доступна только пользователям с соответствующим правом.", icon: IconHistory, items: [{ title: "Марина К. обновила hero", detail: "Главная · заголовок · 12 мин назад", status: "Сохранено", tone: "success" }, { title: "Олег М. изменил посадочную", detail: "Отдых с детьми · 34 мин назад", status: "Черновик", tone: "warning" }, { title: "Не обработано изображение", detail: "bath-gallery.tiff · формат не поддерживается", status: "Ошибка", tone: "warning" }] },
}

export function ManagementPage({ mode }: { mode?: "footer" | "component" }) {
  const location = useLocation(); const key = mode === "footer" ? "/globals/navigation" : mode === "component" ? "/components" : location.pathname; const data = pages[key]!
  const demo = cmsRepository.mode === "api"
  return <PageFrame><PageHeading actions={<Button disabled={demo} onClick={() => window.alert("Действие создаст draft за repository boundary") } size="sm" title={demo ? "Для этого раздела authoritative API ещё не реализован" : undefined}><IconPlus />Создать</Button>} description={data.description} title={mode === "footer" ? "Footer" : data.title} />{demo ? <Alert className="mb-3 border-warning/30"><IconAlertTriangle /><AlertTitle>Демонстрационная спецификация</AlertTitle><AlertDescription>Карточки ниже показывают запланированную структуру и состояния, а не серверные данные. Изменения отключены до появления authoritative API этого раздела.</AlertDescription></Alert> : null}<div className="space-y-2">{data.items.map((item) => <div className="flex min-h-16 items-center gap-3 rounded-xl border bg-background px-4 py-3" key={item.title}><IconBox icon={data.icon} size="sm" variant={item.tone === "warning" ? "warning" : item.tone === "success" ? "success" : "info"} /><div className="min-w-0 flex-1"><p className="text-xs font-medium">{item.title}</p><p className="mt-0.5 truncate text-[10px] text-muted-foreground">{item.detail}</p></div>{key === "/settings/integrations" ? <SourceMarker source="computed" /> : null}{demo ? <StatusBadge tone="neutral">Demo</StatusBadge> : <StatusBadge tone={item.tone}>{item.status}</StatusBadge>}{item.href && !demo ? <Link className="text-primary" to={item.href}><IconArrowRight className="size-4" /></Link> : <Button aria-label={`Открыть ${item.title}`} disabled={demo} onClick={() => window.alert(`${item.title}: editor подключится к admin API в следующем этапе`) } size="icon-xs" title={demo ? "Backend API ещё не реализован" : undefined} variant="ghost"><IconArrowRight /></Button>}</div>)}</div></PageFrame>
}
