import { useCallback, useState } from "react"
import { IconAlertTriangle, IconGitCompare, IconHistory, IconRefresh, IconRocket } from "@tabler/icons-react"
import { Link, useParams } from "react-router-dom"

import { Alert, AlertDescription, AlertTitle, Button, EditorSection, ListRow, ListSection, LoadingRows, PageFrame, PageState, StatusBadge } from "@crm/ui"
import { PageHeading, ReleaseGateRow } from "@admin/components/cms-ui"
import { cmsRepository } from "@admin/data/cms-repository"
import type { ReleaseRecord } from "@admin/entities/cms"
import { useRepository } from "@admin/features/use-repository"
import { useAdminAuthSession } from "@admin/features/auth-session-context"

const releaseStatus: Record<ReleaseRecord["state"], { label: string; tone: "neutral" | "warning" | "success" | "danger" | "info" }> = {
  draft: { label: "Черновик", tone: "neutral" }, review: { label: "На проверке", tone: "warning" }, approved: { label: "Готов", tone: "info" }, published: { label: "Опубликован", tone: "success" }, failed: { label: "Ошибка", tone: "danger" },
}

export function ReleasesPage() {
  const loader = useCallback(() => cmsRepository.getReleases(), [])
  const state = useRepository(loader)
  return <PageFrame><PageHeading description="Immutable releases, public API/CDN delivery, retry и rollback." title="Журнал публикаций" />{state.loading ? <div className="rounded-xl border bg-background"><LoadingRows count={5} /></div> : state.error ? <PageState actionLabel="Повторить" icon={IconAlertTriangle} onAction={state.reload} title="Публикации недоступны">{state.error}</PageState> : <div className="space-y-2">{state.data?.map((release) => <Link className="flex items-center gap-3 rounded-xl border bg-background p-4 hover:bg-muted/30" key={release.id} to={`/releases/${release.id}`}><span className="flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><IconRocket className="size-5" /></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><strong className="text-[13px]">{release.title}</strong><StatusBadge tone={releaseStatus[release.state].tone}>{releaseStatus[release.state].label}</StatusBadge>{release.active ? <StatusBadge tone="success">Active</StatusBadge> : null}</span><span className="mt-1 block text-[10px] text-muted-foreground">{release.id} · {release.changedRoutes} URL · {release.createdLabel}</span></span><DeliverySummary release={release} /></Link>)}</div>}</PageFrame>
}

export function ReleaseDetailPage() {
  const { user } = useAdminAuthSession()
  const { releaseId = "" } = useParams()
  const loader = useCallback(() => cmsRepository.getRelease(releaseId), [releaseId])
  const state = useRepository(loader)
  const [working, setWorking] = useState(false)
  const [actionError, setActionError] = useState<string>()
  if (state.error) return <PageFrame><PageState actionLabel="Повторить" icon={IconAlertTriangle} onAction={state.reload} title="Релиз недоступен">{state.error}</PageState></PageFrame>
  if (state.loading || !state.data) return <PageFrame><LoadingRows count={7} /></PageFrame>
  const release = state.data
  const run = async (action: () => Promise<unknown>) => { setWorking(true); setActionError(undefined); try { await action(); await state.reload() } catch (error) { setActionError(error instanceof Error ? error.message : "Операция не выполнена") } finally { setWorking(false) } }
  const stale = release.state === "approved" && release.activeReleaseId !== undefined && release.baseReleaseId !== (release.activeReleaseId ?? "—")
  return <PageFrame width="full"><PageHeading actions={release.state === "approved" ? <Button disabled={working || stale || release.activeReleaseVersion === undefined || user.capabilities.canPublishContent !== true} onClick={() => void run(() => cmsRepository.activateRelease(release.id, release.activeReleaseId ?? null, release.activeReleaseVersion!))}><IconRocket />Активировать</Button> : undefined} description={`Base ${release.baseReleaseId} · immutable manifest · ${release.createdLabel}`} title={release.title} />
    {actionError ? <Alert className="mb-3" variant="destructive"><IconAlertTriangle /><AlertTitle>Операция не выполнена</AlertTitle><AlertDescription>{actionError}</AlertDescription></Alert> : null}
    {stale ? <Alert className="mb-3" variant="destructive"><IconAlertTriangle /><AlertTitle>Preview устарел</AlertTitle><AlertDescription>Active release изменился; этот release нужно собрать заново.</AlertDescription></Alert> : null}
    <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-3"><EditorSection actions={<StatusBadge tone={releaseStatus[release.state].tone}>{releaseStatus[release.state].label}</StatusBadge>} subtitle="Release-owned URL/cache blast radius." title="Затронутые страницы"><div className="divide-y rounded-lg border">{release.changes.map((change) => <div className="grid gap-1 px-3 py-3 text-xs sm:grid-cols-[1fr_180px]" key={change.route}><span className="font-mono">{change.route}</span><span className="text-muted-foreground">{change.kind}</span></div>)}</div></EditorSection><EditorSection title="Validation и delivery gates"><div className="divide-y rounded-lg border">{release.gates.map((gate) => <ReleaseGateRow gate={gate} key={gate.id} />)}</div></EditorSection><DeliveryPanel canReplay={user.capabilities.canManageIntegrations === true} release={release} working={working} replay={(delivery) => void run(() => cmsRepository.replayReleaseDelivery(release.id, delivery))} /></div>
      <aside className="space-y-3"><section className="overflow-hidden rounded-xl border bg-background"><ListSection count={5} icon={IconGitCompare} title="Manifest"><ListRow><Summary label="Release" value={release.id} /></ListRow><ListRow><Summary label="Base" value={release.baseReleaseId} /></ListRow><ListRow><Summary label="Routes" value={String(release.changedRoutes)} /></ListRow><ListRow><Summary label="Assets" value={String(release.assets)} /></ListRow><ListRow><Summary label="Code" value={String(release.codeArtifacts)} /></ListRow></ListSection></section><EditorSection title="Rollback"><p className="text-[10px] leading-4 text-muted-foreground">Rollback создаёт новый immutable release и атомарно переключает active pointer.</p><Button className="mt-3 w-full" disabled={working || release.active || release.state !== "published" || release.activeReleaseVersion === undefined || user.capabilities.canPublishContent !== true} onClick={() => void run(() => cmsRepository.rollbackRelease(release.id, release.activeReleaseId ?? null, release.activeReleaseVersion!))} variant="outline"><IconHistory />Откатить к этому release</Button></EditorSection></aside></div>
  </PageFrame>
}

function DeliveryPanel({ canReplay, release, replay, working }: { canReplay: boolean; release: ReleaseRecord; replay: (delivery: NonNullable<ReleaseRecord["delivery"]>[number]) => void; working: boolean }) { return <EditorSection title="Public API / CDN delivery"><div className="divide-y rounded-lg border">{release.delivery?.length ? release.delivery.map((delivery) => <div className="flex items-center gap-3 p-3" key={`${delivery.eventId}:${delivery.consumer}`}><span className="min-w-0 flex-1"><strong className="block text-xs">{delivery.consumer}</strong><span className="text-[10px] text-muted-foreground">epoch {delivery.deliveryEpoch} · attempts {delivery.attempts}{delivery.lastErrorCode ? ` · ${delivery.lastErrorCode}` : ""}</span></span><StatusBadge tone={delivery.status === "succeeded" ? "success" : delivery.status === "failed" || delivery.status === "dead_letter" ? "danger" : "info"}>{delivery.status}</StatusBadge>{delivery.status === "failed" || delivery.status === "dead_letter" ? <Button disabled={working || !canReplay} onClick={() => replay(delivery)} size="xs" title={canReplay ? undefined : "Нет capability canManageIntegrations"} variant="outline"><IconRefresh />Повторить</Button> : null}</div>) : <p className="p-3 text-xs text-muted-foreground">Delivery event ещё не создан или consumers не зарегистрированы.</p>}</div></EditorSection> }
function DeliverySummary({ release }: { release: ReleaseRecord }) { const failed = release.delivery?.some((item) => item.status === "failed" || item.status === "dead_letter"); const running = release.delivery?.some((item) => item.status === "pending" || item.status === "processing"); return <StatusBadge tone={failed ? "danger" : running ? "info" : release.delivery?.length ? "success" : "neutral"}>{failed ? "Delivery failed" : running ? "Delivering" : release.delivery?.length ? "Delivered" : "No delivery"}</StatusBadge> }
function Summary({ label, value }: { label: string; value: string }) { return <div className="flex min-h-11 items-center justify-between gap-3 px-4 py-2"><span className="text-[10px] text-muted-foreground">{label}</span><strong className="max-w-48 truncate text-xs">{value}</strong></div> }
