export type DomainErrorCode =
  | "INVALID_INTERVAL" | "INVALID_MONEY" | "CURRENCY_MISMATCH" | "INVALID_STATE_TRANSITION"
  | "CAPACITY_EXCEEDED" | "PERMISSION_DENIED" | "INVALID_IDEMPOTENCY_INPUT"
  | "IDEMPOTENCY_CONFLICT" | "PAYMENT_IMMUTABLE" | "PAYMENT_INVALID"
  | "HOUSE_QUOTE_INVALID_PERIOD" | "HOUSE_QUOTE_UNSUPPORTED_QUANTITY" | "CAMPGROUND_QUOTE_UNSUPPORTED_QUANTITY"
  | "OFFERING_NOT_QUOTABLE" | "PRICE_BOOK_NOT_ACTIVE" | "PRICE_BOOK_MISMATCH"
  | "PRICE_BOOK_COVERAGE_GAP" | "PRICING_CURRENCY_MISMATCH" | "PRICING_TIMEZONE_MISMATCH"
  | "RATE_PLAN_NOT_FOUND" | "RATE_PLAN_DEFAULT_AMBIGUOUS" | "RATE_PLAN_BASIS_UNSUPPORTED"
  | "PRICE_QUANTITY_REQUIRED" | "PRICE_QUANTITY_OUT_OF_RANGE" | "CALENDAR_NOT_ACTIVE"
  | "CALENDAR_DATE_MISSING" | "CALENDAR_DATE_AMBIGUOUS" | "PRICE_RULE_INVALID"
  | "PRICE_RULE_AMBIGUOUS" | "PRICE_AMOUNT_OVERFLOW" | "QUOTE_CLOCK_INVALID"
  | "QUOTE_SERVICE_DATE_IN_PAST" | "QUOTE_TTL_INVALID" | "UNSUPPORTED_PRICING_DIMENSION"
  | "PROGRAM_TEMPLATE_MISMATCH" | "PROGRAM_QUOTE_INVALID_DATE" | "PROGRAM_DURATION_MISMATCH" | "PRICE_DURATION_OUT_OF_RANGE"
  | "CALENDAR_INVALID_COVERAGE" | "CALENDAR_IMMUTABLE" | "CALENDAR_INVALID_TRANSITION"
  | "OFFERING_BINDING_INVALID" | "OFFERING_ADDON_INVALID"
  | "QUOTE_SNAPSHOT_EXPIRED" | "QUOTE_ACCEPTANCE_INVALID" | "QUOTE_ALREADY_ACCEPTED"
  | "QUOTE_ACCEPTANCE_TARGET_VERSION_CONFLICT" | "QUOTE_NOT_ACCEPTANCE_READY"
  | "PROMOTION_INACTIVE" | "PROMOTION_NOT_STACKABLE" | "PROMOTION_INVALID_AMOUNT" | "PROMOTION_NOT_APPLICABLE" | "PROMOTION_MINIMUM_NOT_MET";

export class DomainError extends Error {
  readonly code: DomainErrorCode;
  readonly fieldErrors: Readonly<Record<string, readonly string[]>>;
  readonly details: Readonly<Record<string, unknown>>;

  constructor(code: DomainErrorCode, message: string, options: {
    fieldErrors?: Record<string, readonly string[]>;
    details?: Record<string, unknown>;
  } = {}) {
    super(message);
    this.name = "DomainError";
    this.code = code;
    this.fieldErrors = options.fieldErrors ?? {};
    this.details = options.details ?? {};
  }
}

export function assertDomain(condition: unknown, code: DomainErrorCode, message: string): asserts condition {
  if (!condition) throw new DomainError(code, message);
}
