import { z } from "zod";

export const ErrorCodeSchema = z.enum([
  "VALIDATION_ERROR", "AUTHENTICATION_REQUIRED", "AUTHORIZATION_DENIED", "NOT_FOUND",
  "CONFLICT", "RESOURCE_CONFLICT", "STALE_VERSION", "IDEMPOTENCY_CONFLICT",
  "INVALID_STATE_TRANSITION", "CAPACITY_EXCEEDED", "PAYMENT_INVALID", "PAYMENT_IMMUTABLE",
  "RATE_LIMITED", "INTERNAL_ERROR",
  "UNAUTHENTICATED", "PERMISSION_DENIED", "CSRF_REJECTED", "INVALID_CREDENTIALS",
  "INVALID_CURRENT_PASSWORD", "INVALID_CURSOR", "INVALID_INTERVAL", "INVALID_AMOUNT",
  "VERSION_CONFLICT", "CURRENCY_MISMATCH", "DUPLICATE", "REFUND_LIMIT_EXCEEDED",
  "BOOKING_ITEM_NOT_FOUND", "BOOKING_NOT_FOUND", "CUSTOMER_NOT_FOUND", "LEAD_NOT_FOUND",
  "RESOURCE_NOT_FOUND", "RESOURCE_ARCHIVED", "RESOURCE_BLOCK_NOT_FOUND",
  "RESOURCE_ALLOCATION_NOT_FOUND", "PROGRAM_TEMPLATE_NOT_FOUND", "PROGRAM_OCCURRENCE_NOT_FOUND",
  "PROGRAM_REGISTRATION_NOT_FOUND", "PROGRAM_CATEGORY_NOT_FOUND", "EVENT_NOT_FOUND",
  "EVENT_CATEGORY_NOT_FOUND", "PAYMENT_SOURCE_INVALID", "SAVED_VIEW_NOT_FOUND", "TASK_NOT_FOUND",
  "TEMPLATE_ARCHIVED", "USER_NOT_FOUND", "CMS_NODE_NOT_FOUND", "CMS_DRAFT_REQUIRED",
  "CMS_NODE_ARCHIVED", "CMS_PARENT_INVALID", "CMS_PARENT_CYCLE", "CMS_PREVIEW_UNAVAILABLE",
  "CMS_RELEASE_INVALID", "CMS_ROUTE_INVALID", "CMS_REDIRECT_REQUIRED", "CMS_SUBTREE_MOVE_REQUIRED",
  "OFFERING_NOT_FOUND", "OFFERING_KIND_UNSUPPORTED", "PRICE_BOOK_NOT_FOUND",
  "PRICE_BOOK_NOT_DRAFT", "PRICE_BOOK_PERIOD_CONFLICT", "PRICE_BOOK_VALIDATION_FAILED",
  "PRICE_BOOK_ACTIVATION_TOO_EARLY", "PRICE_BOOK_ACTIVATION_EXPIRED", "BUSINESS_CALENDAR_NOT_ACTIVE", "BUSINESS_CALENDAR_GAP",
  "HOUSE_QUOTE_INVALID_PERIOD", "HOUSE_QUOTE_UNSUPPORTED_QUANTITY", "OFFERING_NOT_QUOTABLE",
  "PRICE_BOOK_NOT_ACTIVE", "PRICE_BOOK_MISMATCH", "PRICE_BOOK_COVERAGE_GAP",
  "PRICING_CURRENCY_MISMATCH", "PRICING_TIMEZONE_MISMATCH", "RATE_PLAN_NOT_FOUND",
  "RATE_PLAN_DEFAULT_AMBIGUOUS", "RATE_PLAN_BASIS_UNSUPPORTED", "PRICE_QUANTITY_REQUIRED",
  "PRICE_QUANTITY_OUT_OF_RANGE", "CALENDAR_NOT_ACTIVE", "CALENDAR_DATE_MISSING",
  "CALENDAR_DATE_AMBIGUOUS", "PRICE_RULE_INVALID", "PRICE_RULE_AMBIGUOUS",
  "PRICE_AMOUNT_OVERFLOW", "QUOTE_CLOCK_INVALID", "QUOTE_SERVICE_DATE_IN_PAST",
  "QUOTE_TTL_INVALID", "UNSUPPORTED_PRICING_DIMENSION",
]);
export type ErrorCode = z.infer<typeof ErrorCodeSchema>;

export const FieldErrorsSchema = z.record(z.string().min(1), z.array(z.string().min(1)));
export type FieldErrors = z.infer<typeof FieldErrorsSchema>;

export const ApiErrorSchema = z.object({
  code: ErrorCodeSchema,
  message: z.string().min(1),
  fieldErrors: FieldErrorsSchema.optional(),
  details: z.record(z.string(), z.unknown()).default({}),
  requestId: z.string().min(1).optional(),
}).strict();
export type ApiError = z.infer<typeof ApiErrorSchema>;

export function toApiError(error: unknown, fallback: Pick<ApiError, "code" | "message"> = {
  code: "INTERNAL_ERROR", message: "Внутренняя ошибка",
}): ApiError {
  const parsed = ApiErrorSchema.safeParse(error);
  if (parsed.success) return parsed.data;
  return { ...fallback, details: {} };
}
