import { randomUUID } from "node:crypto"

import { ConflictException, ForbiddenException, Inject, Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common"
import { Brackets, DataSource, type EntityManager } from "typeorm"

import type { EventArchive, EventCreate, EventDto, EventListQuery, EventTransition, EventUpdate, SessionUser } from "@crm/contracts"
import { ChangeLogEntity, EventEntity, IdempotencyKeyEntity, OutboxEventEntity } from "@crm/db"
import { ensureCmsSourceDraft } from "../cms/cms-source-draft.js"

@Injectable()
export class EventsService {
  constructor(@Inject(DataSource) private readonly dataSource: DataSource) {}

  async list(query: EventListQuery, actor: SessionUser): Promise<{ items: EventDto[]; nextCursor: string | null }> {
    this.assert(actor, "canView")
    const builder = this.dataSource.getRepository(EventEntity).createQueryBuilder("event").where(query.archived === true ? "event.archived_at IS NOT NULL" : "event.archived_at IS NULL")
    if (query.status) builder.andWhere("event.status = :status", { status: query.status }); if (query.categoryId) builder.andWhere("event.category_id = :categoryId", { categoryId: query.categoryId }); if (query.customerId) builder.andWhere("event.customer_id = :customerId", { customerId: query.customerId }); if (query.requiresAction !== undefined) builder.andWhere("event.requires_action = :requiresAction", { requiresAction: query.requiresAction }); if (query.unpaid === true) builder.andWhere("event.paid_amount < event.total_amount"); if (query.from) builder.andWhere("event.starts_at >= :from", { from: new Date(query.from) }); if (query.to) builder.andWhere("event.starts_at < :to", { to: new Date(query.to) }); if (query.cursor) builder.andWhere("event.starts_at > :cursor", { cursor: new Date(query.cursor) }); builder.orderBy("event.starts_at", "ASC").take(query.limit + 1)
    const rows = await builder.getMany(); const page = rows.slice(0, query.limit); return { items: page.map((row) => this.dto(row, actor)), nextCursor: rows.length > query.limit ? page.at(-1)?.startsAt.toISOString() ?? null : null }
  }
  async get(idOrCode: string, actor: SessionUser) { this.assert(actor, "canView"); return this.dto(await this.find(this.dataSource.manager, idOrCode), actor) }
  async create(input: EventCreate, actor: SessionUser, requestId: string) { this.assert(actor, "canCreate"); return this.dataSource.transaction(async (manager) => { const hash = JSON.stringify(input); const replay = await this.replay(manager, "event:create", input.operationId, input.idempotencyKey, hash); if (replay) return replay; const row = manager.create(EventEntity, { id: randomUUID(), code: input.code ?? `E-${await this.next(manager)}`, name: input.name, categoryId: input.categoryId, customerId: input.customerId, phone: input.phone, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), guestCount: input.guestCount, totalAmount: input.total.amountMinor, paidAmount: 0, currency: input.total.currency, status: input.status, comment: input.comment, requiresAction: input.requiresAction, assigneeIds: input.assigneeIds, scenario: input.scenario.map((stage) => ({ ...stage, id: stage.id ?? randomUUID() })), createdBy: actor.id, updatedBy: actor.id, archivedAt: null }); const saved = await manager.save(row); const response = this.dto(saved, actor); await this.mutate(manager, saved, "created", actor.id, requestId, response); await ensureCmsSourceDraft(manager, { sourceKind: "event", sourceId: saved.id, sourceVersion: saved.version, title: saved.name, actorId: actor.id, requestId }); await this.remember(manager, "event:create", input.operationId, input.idempotencyKey, hash, response); return response }) }
  async update(idOrCode: string, input: EventUpdate, actor: SessionUser, requestId: string) { this.assert(actor, "canEdit"); return this.dataSource.transaction(async (manager) => { const hash = JSON.stringify(input); const replay = await this.replay(manager, `event:${idOrCode}:update`, input.operationId, input.idempotencyKey, hash); if (replay) return replay; const current = await this.find(manager, idOrCode); this.assertVersion(current, input.version); if (input.total && input.total.currency !== current.currency) throw new ConflictException({ code: "CURRENCY_MISMATCH", message: "Валюта мероприятия неизменяема" }); const patch: Partial<EventEntity> = { ...(input.name === undefined ? {} : { name: input.name }), ...(input.categoryId === undefined ? {} : { categoryId: input.categoryId }), ...(input.customerId === undefined ? {} : { customerId: input.customerId }), ...(input.phone === undefined ? {} : { phone: input.phone }), ...(input.startsAt === undefined ? {} : { startsAt: new Date(input.startsAt) }), ...(input.endsAt === undefined ? {} : { endsAt: new Date(input.endsAt) }), ...(input.guestCount === undefined ? {} : { guestCount: input.guestCount }), ...(input.total === undefined ? {} : { totalAmount: input.total.amountMinor }), ...(input.comment === undefined ? {} : { comment: input.comment }), ...(input.requiresAction === undefined ? {} : { requiresAction: input.requiresAction }), ...(input.assigneeIds === undefined ? {} : { assigneeIds: input.assigneeIds }), ...(input.scenario === undefined ? {} : { scenario: input.scenario.map((stage) => ({ ...stage, id: stage.id ?? randomUUID() })) }), updatedBy: actor.id }; const result = await manager.createQueryBuilder().update(EventEntity).set({ ...patch, version: () => '"version" + 1', updatedAt: () => "now()" }).where("id = :id AND version = :version", { id: current.id, version: input.version }).execute(); if (result.affected !== 1) throw this.versionConflict(current); const saved = await manager.findOneByOrFail(EventEntity, { id: current.id }); const response = this.dto(saved, actor); await this.mutate(manager, saved, "updated", actor.id, requestId, { before: this.dto(current, actor), after: response }); await this.remember(manager, `event:${idOrCode}:update`, input.operationId, input.idempotencyKey, hash, response); return response }) }
  async transition(idOrCode: string, input: EventTransition, actor: SessionUser, requestId: string) { this.assert(actor, "canChangeStatus"); if (input.quoteAcceptance) throw new UnprocessableEntityException({ code: "QUOTE_TARGET_UNSUPPORTED", message: "Принятие quote для Event ещё не поддерживается" }); return this.dataSource.transaction(async (manager) => { const hash = JSON.stringify(input); const replay = await this.replay(manager, `event:${idOrCode}:transition`, input.operationId, input.idempotencyKey, hash); if (replay) return replay; const current = await this.find(manager, idOrCode); this.assertVersion(current, input.version); const allowed: Record<string, string[]> = { inquiry: ["planning", "cancelled"], planning: ["booked", "cancelled"], booked: ["completed", "cancelled"], completed: [], cancelled: [] }; if (!allowed[current.status]?.includes(input.status)) throw new ConflictException({ code: "INVALID_STATE_TRANSITION", message: `Нельзя перевести мероприятие из ${current.status} в ${input.status}` }); const result = await manager.createQueryBuilder().update(EventEntity).set({ status: input.status, updatedBy: actor.id, version: () => '"version" + 1', updatedAt: () => "now()" }).where("id = :id AND version = :version", { id: current.id, version: input.version }).execute(); if (result.affected !== 1) throw this.versionConflict(current); const saved = await manager.findOneByOrFail(EventEntity, { id: current.id }); const response = this.dto(saved, actor); await this.mutate(manager, saved, "transitioned", actor.id, requestId, { from: current.status, to: input.status }); await this.remember(manager, `event:${idOrCode}:transition`, input.operationId, input.idempotencyKey, hash, response); return response }) }
  async archive(idOrCode: string, input: EventArchive, actor: SessionUser, requestId: string) { this.assert(actor, "canArchive"); return this.dataSource.transaction(async (manager) => { const hash = JSON.stringify(input); const replay = await this.replay(manager, `event:${idOrCode}:archive`, input.operationId, input.idempotencyKey, hash); if (replay) return replay; const current = await this.find(manager, idOrCode); this.assertVersion(current, input.version); const result = await manager.createQueryBuilder().update(EventEntity).set({ archivedAt: new Date(), updatedBy: actor.id, version: () => '"version" + 1', updatedAt: () => "now()" }).where("id = :id AND version = :version", { id: current.id, version: input.version }).execute(); if (result.affected !== 1) throw this.versionConflict(current); const saved = await manager.findOneByOrFail(EventEntity, { id: current.id }); const response = this.dto(saved, actor); await this.mutate(manager, saved, "archived", actor.id, requestId, response); await this.remember(manager, `event:${idOrCode}:archive`, input.operationId, input.idempotencyKey, hash, response); return response }) }
  private dto(row: EventEntity, actor: SessionUser): EventDto { return { id: row.id, version: row.version, code: row.code, name: row.name, categoryId: row.categoryId, customerId: row.customerId, phone: row.phone, startsAt: row.startsAt.toISOString(), endsAt: row.endsAt.toISOString(), guestCount: row.guestCount, total: { amountMinor: row.totalAmount, currency: row.currency }, paid: { amountMinor: row.paidAmount, currency: row.currency }, status: row.status as EventDto["status"], comment: row.comment, requiresAction: row.requiresAction, hasConflict: false, assigneeIds: row.assigneeIds, scenario: (row.scenario ?? []).map((stage) => ({ id: String(stage.id), name: String(stage.name), durationMinutes: Number(stage.durationMinutes), comment: String(stage.comment ?? "") })), archived: row.archivedAt !== null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), capabilities: { canView: actor.capabilities.canView, canCreate: actor.capabilities.canCreate, canEdit: actor.capabilities.canEdit, canArchive: actor.capabilities.canArchive, canChangeStatus: actor.capabilities.canChangeStatus, canOverrideConflict: actor.capabilities.canOverrideConflict } } }
  private assert(actor: SessionUser, key: keyof SessionUser["capabilities"]) { if (!actor.capabilities[key]) throw new ForbiddenException({ code: "PERMISSION_DENIED", message: `Capability ${key} is required` }) }
  private assertVersion(row: { version: number; id: string }, version: number) { if (row.version !== version) throw this.versionConflict(row) }
  private versionConflict(row: { id: string; version: number }) { return new ConflictException({ code: "VERSION_CONFLICT", message: "Мероприятие было изменено другим сотрудником", details: { entityId: row.id, serverVersion: row.version } }) }
  private async find(manager: EntityManager, idOrCode: string) { const row = await manager.getRepository(EventEntity).findOne({ where: /^[0-9a-f-]{36}$/i.test(idOrCode) ? { id: idOrCode } : { code: idOrCode } }); if (!row) throw new NotFoundException({ code: "EVENT_NOT_FOUND", message: "Мероприятие не найдено" }); return row }
  private async next(manager: EntityManager) { const result = await manager.query(`SELECT nextval('event_code_seq')::text AS nextval`) as Array<{ nextval: string }>; return result[0]!.nextval }
  private async mutate(manager: EntityManager, entity: EventEntity, action: string, actorId: string, requestId: string, changes: unknown) { const now = new Date(); await manager.getRepository(ChangeLogEntity).save(manager.create(ChangeLogEntity, { id: randomUUID(), entityType: "event", entityId: entity.id, action, actorId, requestId, changes: changes as Record<string, unknown>, createdAt: now })); await manager.getRepository(OutboxEventEntity).save(manager.create(OutboxEventEntity, { id: randomUUID(), topic: `event.${action}`, aggregateType: "event", aggregateId: entity.id, payload: { eventId: entity.id, version: entity.version }, availableAt: now, processedAt: null, attempts: 0, createdAt: now })) }
  private async replay(manager: EntityManager, scope: string, operationId: string, idempotencyKey: string, requestHash: string) { const row = await manager.getRepository(IdempotencyKeyEntity).createQueryBuilder("key").where("key.scope = :scope", { scope }).andWhere(new Brackets((q) => q.where("key.operation_id = :operationId", { operationId }).orWhere("key.idempotency_key = :idempotencyKey", { idempotencyKey }))).getOne(); if (!row) return null; if (row.requestHash !== requestHash) throw new ConflictException({ code: "IDEMPOTENCY_CONFLICT", message: "Ключ идемпотентности уже использован с другими данными" }); if (row.responseBody) return row.responseBody; throw new ConflictException({ code: "IDEMPOTENCY_CONFLICT", message: "Операция уже выполняется" }) }
  private async remember(manager: EntityManager, scope: string, operationId: string, idempotencyKey: string, requestHash: string, response: unknown) { await manager.getRepository(IdempotencyKeyEntity).save(manager.create(IdempotencyKeyEntity, { id: randomUUID(), scope, operationId, idempotencyKey, requestHash, responseStatus: 200, responseBody: response as Record<string, unknown>, createdAt: new Date() })) }
}
