import { expect, test } from "@playwright/test"

test("reads changed CRM prices in the card, popup and request form without a new release", async ({ request, page }) => {
  await request.post("http://127.0.0.1:4398/__scenario?name=commerce-published")
  const initial = await request.get("/")
  expect(initial.status()).toBe(200)
  expect(initial.headers()["cache-control"]).toContain("no-store")
  await page.goto("/")
  await expect(page.locator("#houses")).toContainText(/6\s*500\s*₽/)
  await expect(page.locator("#events")).toContainText(/от 2\s*500\s*₽\s*·\s*за участника/)
  await expect(page.locator("#programs")).toContainText(/от 2\s*500\s*₽\s*·\s*за участника/)
  await expect(page.locator("#venues")).toContainText(/от 3\s*200\s*₽\s*·\s*за час/)
  await expect(page.locator("#quiz [data-calculated-price]").first()).toHaveText(/от 6\s*500\s*₽/)
  const card = page.locator("#houses").getByRole("button").first()
  await card.scrollIntoViewIfNeeded()
  await expect(page.locator('astro-island[component-url*="HousesIsland"]')).not.toHaveAttribute("ssr", "")
  await card.click()
  const dialog = page.getByRole("dialog", { name: "Домик из CMS", exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText(/от 6\s*500\s*₽/)
  await expect(dialog).toContainText("за ночь")
  await expect(dialog).not.toContainText("Доступность на ближайшие")
  await expect(dialog.locator("img")).toHaveCount(0)
  await page.keyboard.press("Escape")
  await expect(dialog).not.toBeVisible()
  const updated = await request.post("http://127.0.0.1:4398/__house-price?amountMinor=875025")
  expect((await updated.json()).releaseId).toBe("22222222-2222-4222-8222-222222222222")
  await page.reload()
  await expect(page.locator("#houses")).toContainText(/8\s*750,25\s*₽/)
  await expect(page.locator("#quiz [data-calculated-price]").first()).toHaveText(/от 8\s*750,25\s*₽/)
  await expect(page.locator("#sauna")).toContainText("Подробности скоро")
  await expect(page.locator("#events")).toContainText("Программа из CMS")
  await expect(page.locator("#events [data-event-day]")).toHaveText("20")
  for (const text of ["Кедровая русская баня", "Фермерский сет", "Панорамный", "480+", "WINTER20"]) await expect(page.locator("body")).not.toContainText(text)
  await expect(page.locator('#houses img, #venues img, #programs img, #events img, #quiz img')).toHaveCount(0)
  const quiz = page.locator("#quiz")
  await quiz.scrollIntoViewIfNeeded()
  await expect(page.locator('astro-island[component-url*="BookingQuizIsland"]')).not.toHaveAttribute("ssr", "")
  await quiz.getByRole("button", { name: "Далее", exact: true }).click()
  await expect(quiz).toContainText("Желаемые даты. Доступность проверит менеджер.")
  await expect(quiz.getByRole("gridcell", { name: /недоступно/ })).toHaveCount(0)
  await expect(quiz.getByRole("textbox", { name: "Промокод" })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test("shows request-only pricing without invented amounts", async ({ request, page }) => {
  await request.post("http://127.0.0.1:4398/__scenario?name=commerce-request")
  await page.goto("/")
  await expect(page.locator("#houses")).toContainText("По запросу")
  await expect(page.locator("#programs")).toContainText("По запросу")
  await expect(page.locator("#venues")).toContainText("По запросу")
  await expect(page.locator("#quiz [data-calculated-price]").first()).toHaveText("По запросу")
})

test("renders manually ordered CRM cards across cursor pages while events remain automatic", async ({ request, page }) => {
  await request.post("http://127.0.0.1:4398/__scenario?name=commerce-curated")
  const response = await page.goto("/")
  expect(response?.status()).toBe(200)
  const houses = page.locator("#houses")
  await expect(houses).toBeVisible()
  await expect(houses.getByRole("button").first()).toContainText("Второй домик из CMS")
  await expect(houses.getByRole("button").nth(1)).toContainText("Домик из CMS")
  await expect(page.locator("#programs")).toContainText("Пока нет доступных программ")
  await expect(page.locator("#venues")).toContainText("Пока нет доступных площадок")
  await expect(page.locator("#events")).toContainText("Программа из CMS")
})

test("keeps authored sections visible without inventing cards for empty CRM catalogs", async ({ request, page }) => {
  await request.post("http://127.0.0.1:4398/__scenario?name=commerce-empty")
  const response = await page.goto("/")
  expect(response?.status()).toBe(200)
  await expect(page.locator("#houses, #quiz")).toHaveCount(0)
  await expect(page.locator("#events")).toContainText("Пока нет ближайших событий")
  await expect(page.locator("#programs")).toContainText("Пока нет доступных программ")
  await expect(page.locator("#venues")).toContainText("Пока нет доступных площадок")
  await expect(page.locator("#sauna")).toContainText("Подробности скоро")
  await expect(page.locator("#events [data-event-day], #programs .site-program-card, #venues .site-venue-card, #sauna .site-spa-card__content")).toHaveCount(0)
})

for (const scenario of ["outage", "private", "mixed", "mixed-item"]) {
  test(`fails closed for ${scenario} operational catalogs`, async ({ request }) => {
    await request.post(`http://127.0.0.1:4398/__scenario?name=commerce-${scenario}`)
    const response = await request.get("/")
    expect(response.status()).toBe(503)
    const html = await response.text()
    expect(html).not.toContain("PRIVATE_BACKEND_DETAIL")
    expect(html).not.toContain("Домик из CMS")
  })
}

test("does not offer a request when the public projection disables it", async ({ request, page }) => {
  await request.post("http://127.0.0.1:4398/__scenario?name=commerce-unavailable")
  await page.goto("/")
  await expect(page.locator("#quiz")).toHaveCount(0)
  await expect(page.locator("#programs")).toContainText("Пока нет доступных программ")
  await expect(page.locator("#venues")).toContainText("Пока нет доступных площадок")
  await expect(page.locator("#events")).toContainText("Пока нет ближайших событий")
  const card = page.locator("#houses").getByRole("button").first()
  await card.scrollIntoViewIfNeeded()
  await expect(page.locator('astro-island[component-url*="HousesIsland"]')).not.toHaveAttribute("ssr", "")
  await expect(card).toContainText("Временно недоступно")
  await card.click()
  await expect(page.getByRole("dialog", { name: "Домик из CMS" })).toContainText("бронирование приостановлено")
  await expect(page.getByRole("dialog", { name: "Домик из CMS" }).getByRole("button", { name: "Отправить заявку: Домик из CMS" })).toHaveCount(0)
})

test("does not attach fixture promotions to a published hero", async ({ request, page }) => {
  await request.post("http://127.0.0.1:4398/__scenario?name=commerce-hero")
  await page.goto("/")
  await expect(page.locator("#hero")).toContainText("Опубликованный hero")
  for (const code of ["GLAMP3000", "DETI1000", "BIRTHDAY20"]) await expect(page.locator("body")).not.toContainText(code)
})
