export {
  ResourceAllocationCreateSchema,
  ResourceAllocationListQuerySchema,
  ResourceAllocationCancelSchema,
  ResourceAllocationsQuerySchema,
  ResourceArchiveSchema,
  ResourceAvailabilityByCodeQuerySchema,
  ResourceAvailabilityQuerySchema,
  ResourceCreateSchema,
  ResourceListQuerySchema,
  ResourceUpdateSchema,
  ResourceBlockCreateSchema,
  ResourceBlockCancelSchema,
} from "@crm/contracts"

export type {
  ResourceAllocationCreate,
  ResourceAllocationListQuery,
  ResourceAllocationCancel,
  ResourceAllocationsQuery,
  ResourceArchive,
  ResourceAvailabilityByCodeQuery,
  ResourceAvailabilityQuery,
  ResourceCapabilities,
  ResourceReadModel,
  ResourceCreate,
  ResourceDto,
  ResourceListQuery,
  ResourceUpdate,
  ResourceBlockCreate,
  ResourceBlockCancel,
} from "@crm/contracts"
