import { Module } from "@nestjs/common"

import { PublicContentController } from "./public-content.controller.js"
import { PublicContentService } from "./public-content.service.js"
import { CmsSiteSettingsService } from "./cms-site-settings.service.js"
import { PublicSiteSettingsController } from "./public-site-settings.controller.js"
import { PublicMediaController } from "./public-media.controller.js"
import { MediaService } from "./media.service.js"
import { MediaMetricsService } from "./media-metrics.service.js"
import { MediaScannerService } from "./media-scanner.service.js"
import { MediaStorageService } from "./media-storage.service.js"
import { PublicListingController } from "./public-listing.controller.js"
import { PublicListingService } from "./public-listing.service.js"
import { PublicAddonOfferingController } from "./public-addon-offering.controller.js"
import { PublicAddonOfferingService } from "./public-addon-offering.service.js"
import { PublicVenueOfferingController } from "./public-venue-offering.controller.js"
import { PublicVenueOfferingService } from "./public-venue-offering.service.js"
import { PublicHouseOfferingController } from "./public-house-offering.controller.js"
import { PublicHouseOfferingService } from "./public-house-offering.service.js"
import { PublicCampgroundOfferingController } from "./public-campground-offering.controller.js"
import { PublicCampgroundOfferingService } from "./public-campground-offering.service.js"
import { PublicProgramOfferingController } from "./public-program-offering.controller.js"
import { PublicProgramOfferingService } from "./public-program-offering.service.js"
import { PublicEventServiceOfferingController } from "./public-event-service-offering.controller.js"
import { PublicEventServiceOfferingService } from "./public-event-service-offering.service.js"
import { PublicIntakeController } from "../public-intake/public-intake.controller.js"
import { PublicIntakeRateLimiter } from "../public-intake/public-intake-rate-limiter.service.js"
import { PublicIntakeService } from "../public-intake/public-intake.service.js"

@Module({ controllers: [PublicContentController, PublicSiteSettingsController, PublicMediaController, PublicListingController, PublicAddonOfferingController, PublicVenueOfferingController, PublicHouseOfferingController, PublicCampgroundOfferingController, PublicProgramOfferingController, PublicEventServiceOfferingController, PublicIntakeController], providers: [PublicContentService, CmsSiteSettingsService, MediaService, MediaMetricsService, MediaScannerService, MediaStorageService, PublicListingService, PublicAddonOfferingService, PublicVenueOfferingService, PublicHouseOfferingService, PublicCampgroundOfferingService, PublicProgramOfferingService, PublicEventServiceOfferingService, PublicIntakeRateLimiter, PublicIntakeService] })
export class PublicApiModule {}
