import { randomUUID } from "node:crypto"

import { ConflictException, ForbiddenException, Inject, Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common"
import { Brackets, DataSource, type EntityManager } from "typeorm"

import { ProgramRegistrationQuoteResultSchema, type SessionUser } from "@crm/contracts"
import { AcceptedOfferingQuoteLinkEntity, CatalogOfferingEntity, ChangeLogEntity, IdempotencyKeyEntity, OfferingBindingEntity, OfferingQuoteSnapshotEntity, OutboxEventEntity, ProgramOccurrenceEntity, ProgramRegistrationEntity, ProgramTemplateEntity } from "@crm/db"

import type {
  ProgramOccurrenceArchive, ProgramOccurrenceCreate, ProgramOccurrenceListQuery, ProgramOccurrenceTransition, ProgramOccurrenceUpdate,
  ProgramRegistrationArchive, ProgramRegistrationCreate, ProgramRegistrationListQuery, ProgramRegistrationTransition, ProgramRegistrationUpdate, ProgramTemplateArchive, ProgramTemplateCreate, ProgramTemplateListQuery, ProgramTemplateUpdate,
} from "./programs.contracts.js"
import { ensureCmsSourceDraft } from "../cms/cms-source-draft.js"
import { canonicalSha256 } from "../offerings/offering-mutation-support.js"
import { OperationalQuoteAcceptanceService } from "../offerings/operational-quote-acceptance.service.js"

@Injectable()
export class ProgramsService {
  constructor(@Inject(DataSource) private readonly dataSource: DataSource, @Inject(OperationalQuoteAcceptanceService) private readonly quoteAcceptance: OperationalQuoteAcceptanceService) {}

  async listTemplates(query: ProgramTemplateListQuery, actor: SessionUser) {
    this.assert(actor, "canView")
    const builder = this.dataSource.getRepository(ProgramTemplateEntity).createQueryBuilder("template")
      .where(query.archived === true ? "template.archived_at IS NOT NULL" : "template.archived_at IS NULL")
    if (query.publication) builder.andWhere("template.publication = :publication", { publication: query.publication })
    if (query.categoryId) builder.andWhere("template.category_id = :categoryId", { categoryId: query.categoryId })
    if (query.cursor) builder.andWhere("template.created_at < :cursor", { cursor: new Date(query.cursor) })
    builder.orderBy("template.created_at", "DESC").take(query.limit + 1)
    const rows = await builder.getMany(); const page = rows.slice(0, query.limit)
    return { items: page.map((row) => this.templateDto(row, actor)), nextCursor: rows.length > query.limit ? page.at(-1)?.createdAt.toISOString() ?? null : null }
  }

  async getTemplate(idOrCode: string, actor: SessionUser) { this.assert(actor, "canView"); return this.templateDto(await this.findTemplate(this.dataSource.manager, idOrCode), actor) }

  async createTemplate(input: ProgramTemplateCreate, actor: SessionUser, requestId: string) {
    this.assert(actor, "canCreate")
    return this.dataSource.transaction(async (manager) => {
      const replay = await this.replay(manager, "program-template:create", input.operationId, input.idempotencyKey); if (replay) return replay
      const code = input.code ?? `PT-${await this.next(manager, "program_template_code_seq")}`
      const row = manager.create(ProgramTemplateEntity, { id: randomUUID(), code, name: input.name, categoryId: input.categoryId, durationMinutes: input.durationMinutes, minimumParticipants: input.minimumParticipants, participantLimit: input.participantLimit, registrationCloseHours: input.registrationCloseHours, basePriceAmount: input.basePrice.amountMinor, currency: input.basePrice.currency, description: input.description, publication: input.publication, assigneeIds: input.assigneeIds, stages: input.stages.map((stage) => ({ ...stage, id: stage.id ?? randomUUID() })), createdBy: actor.id, updatedBy: actor.id, archivedAt: null })
      const saved = await manager.save(row); const response = this.templateDto(saved, actor); await this.mutate(manager, saved, "program_template", "created", actor.id, requestId, response); await ensureCmsSourceDraft(manager, { sourceKind: "program_template", sourceId: saved.id, sourceVersion: saved.version, title: saved.name, summary: saved.description, actorId: actor.id, requestId }); await this.remember(manager, "program-template:create", input.operationId, input.idempotencyKey, response); return response
    })
  }

  async updateTemplate(idOrCode: string, input: ProgramTemplateUpdate, actor: SessionUser, requestId: string) {
    this.assert(actor, "canEdit")
    return this.dataSource.transaction(async (manager) => {
      const replay = await this.replay(manager, `program-template:${idOrCode}:update`, input.operationId, input.idempotencyKey); if (replay) return replay
      const current = await this.findTemplate(manager, idOrCode); this.assertVersion(current, input.version); const before = this.templateDto(current, actor)
      const patch: Partial<ProgramTemplateEntity> = { ...(input.name === undefined ? {} : { name: input.name }), ...(input.categoryId === undefined ? {} : { categoryId: input.categoryId }), ...(input.durationMinutes === undefined ? {} : { durationMinutes: input.durationMinutes }), ...(input.minimumParticipants === undefined ? {} : { minimumParticipants: input.minimumParticipants }), ...(input.participantLimit === undefined ? {} : { participantLimit: input.participantLimit }), ...(input.registrationCloseHours === undefined ? {} : { registrationCloseHours: input.registrationCloseHours }), ...(input.basePrice === undefined ? {} : { basePriceAmount: input.basePrice.amountMinor, currency: input.basePrice.currency }), ...(input.description === undefined ? {} : { description: input.description }), ...(input.publication === undefined ? {} : { publication: input.publication }), ...(input.assigneeIds === undefined ? {} : { assigneeIds: input.assigneeIds }), ...(input.stages === undefined ? {} : { stages: input.stages.map((stage) => ({ ...stage, id: stage.id ?? randomUUID() })) }), updatedBy: actor.id }
      const result = await manager.createQueryBuilder().update(ProgramTemplateEntity).set({ ...patch, version: () => '"version" + 1', updatedAt: () => "now()" }).where("id = :id AND version = :version", { id: current.id, version: input.version }).execute(); if (result.affected !== 1) throw this.versionConflict(current)
      const saved = await manager.findOneByOrFail(ProgramTemplateEntity, { id: current.id }); const response = this.templateDto(saved, actor); await this.mutate(manager, saved, "program_template", "updated", actor.id, requestId, { before, after: response }); await this.remember(manager, `program-template:${idOrCode}:update`, input.operationId, input.idempotencyKey, response); return response
    })
  }

  async archiveTemplate(idOrCode: string, input: ProgramTemplateArchive, actor: SessionUser, requestId: string) { return this.archiveEntity(idOrCode, input, actor, requestId, "template") }

  async listOccurrences(query: ProgramOccurrenceListQuery, actor: SessionUser) {
    this.assert(actor, "canView"); const builder = this.dataSource.getRepository(ProgramOccurrenceEntity).createQueryBuilder("occurrence").where(query.archived === true ? "occurrence.archived_at IS NOT NULL" : "occurrence.archived_at IS NULL")
    if (query.templateId) builder.andWhere("occurrence.template_id = :templateId", { templateId: query.templateId }); if (query.status) builder.andWhere("occurrence.status = :status", { status: query.status }); if (query.from) builder.andWhere("occurrence.starts_at >= :from", { from: new Date(query.from) }); if (query.to) builder.andWhere("occurrence.starts_at < :to", { to: new Date(query.to) }); if (query.cursor) builder.andWhere("occurrence.starts_at > :cursor", { cursor: new Date(query.cursor) }); builder.orderBy("occurrence.starts_at", "ASC").take(query.limit + 1)
    const rows = await builder.getMany(); const page = rows.slice(0, query.limit); return { items: await Promise.all(page.map((row) => this.occurrenceDto(this.dataSource.manager, row, actor))), nextCursor: rows.length > query.limit ? page.at(-1)?.startsAt.toISOString() ?? null : null }
  }
  async getOccurrence(idOrCode: string, actor: SessionUser) { this.assert(actor, "canView"); return this.occurrenceDto(this.dataSource.manager, await this.findOccurrence(this.dataSource.manager, idOrCode), actor) }
  async createOccurrence(input: ProgramOccurrenceCreate, actor: SessionUser, requestId: string) {
    this.assert(actor, "canCreate"); return this.dataSource.transaction(async (manager) => { const replay = await this.replay(manager, "program-occurrence:create", input.operationId, input.idempotencyKey); if (replay) return replay; const template = await this.findTemplate(manager, input.templateId); if (template.archivedAt) throw new ConflictException({ code: "TEMPLATE_ARCHIVED", message: "Шаблон программы архивирован" }); const code = input.code ?? `PO-${await this.next(manager, "program_occurrence_code_seq")}`; const row = manager.create(ProgramOccurrenceEntity, { id: randomUUID(), code, templateId: template.id, name: input.name ?? template.name, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), participantLimit: input.participantLimit, registrationLimit: input.registrationLimit, status: "draft", currency: input.currency, comment: input.comment, assigneeIds: input.assigneeIds, createdBy: actor.id, updatedBy: actor.id, archivedAt: null }); const saved = await manager.save(row); const response = await this.occurrenceDto(manager, saved, actor); await this.mutate(manager, saved, "program_occurrence", "created", actor.id, requestId, response); await ensureCmsSourceDraft(manager, { sourceKind: "program_occurrence", sourceId: saved.id, sourceVersion: saved.version, title: saved.name, actorId: actor.id, requestId }); await this.remember(manager, "program-occurrence:create", input.operationId, input.idempotencyKey, response); return response })
  }
  async updateOccurrence(idOrCode: string, input: ProgramOccurrenceUpdate, actor: SessionUser, requestId: string) {
    this.assert(actor, "canEdit"); return this.dataSource.transaction(async (manager) => { const replay = await this.replay(manager, `program-occurrence:${idOrCode}:update`, input.operationId, input.idempotencyKey); if (replay) return replay; const resolved = await this.findOccurrence(manager, idOrCode); const current = (await this.lockOccurrences(manager, [resolved.id]))[0]!; this.assertVersion(current, input.version); if (input.participantLimit !== undefined || input.registrationLimit !== undefined) await this.assertOccurrenceLimits(manager, current.id, input.participantLimit ?? current.participantLimit, input.registrationLimit ?? current.registrationLimit); const before = await this.occurrenceDto(manager, current, actor); const patch: Partial<ProgramOccurrenceEntity> = { ...(input.templateId === undefined ? {} : { templateId: input.templateId }), ...(input.name === undefined ? {} : { name: input.name }), ...(input.startsAt === undefined ? {} : { startsAt: new Date(input.startsAt) }), ...(input.endsAt === undefined ? {} : { endsAt: new Date(input.endsAt) }), ...(input.participantLimit === undefined ? {} : { participantLimit: input.participantLimit }), ...(input.registrationLimit === undefined ? {} : { registrationLimit: input.registrationLimit }), ...(input.comment === undefined ? {} : { comment: input.comment }), ...(input.assigneeIds === undefined ? {} : { assigneeIds: input.assigneeIds }), updatedBy: actor.id }; const result = await manager.createQueryBuilder().update(ProgramOccurrenceEntity).set({ ...patch, version: () => '"version" + 1', updatedAt: () => "now()" }).where("id = :id AND version = :version", { id: current.id, version: input.version }).execute(); if (result.affected !== 1) throw this.versionConflict(current); const saved = await manager.findOneByOrFail(ProgramOccurrenceEntity, { id: current.id }); const response = await this.occurrenceDto(manager, saved, actor); await this.mutate(manager, saved, "program_occurrence", "updated", actor.id, requestId, { before, after: response }); await this.remember(manager, `program-occurrence:${idOrCode}:update`, input.operationId, input.idempotencyKey, response); return response })
  }
  async transitionOccurrence(idOrCode: string, input: ProgramOccurrenceTransition, actor: SessionUser, requestId: string) { this.assert(actor, "canChangeStatus"); return this.transitionEntity(idOrCode, input, actor, requestId, "occurrence") }
  async archiveOccurrence(idOrCode: string, input: ProgramOccurrenceArchive, actor: SessionUser, requestId: string) { return this.archiveEntity(idOrCode, input, actor, requestId, "occurrence") }

  async listRegistrations(query: ProgramRegistrationListQuery, actor: SessionUser) { this.assert(actor, "canView"); const builder = this.dataSource.getRepository(ProgramRegistrationEntity).createQueryBuilder("registration").where(query.archived === true ? "registration.archived_at IS NOT NULL" : "registration.archived_at IS NULL"); if (query.occurrenceId) builder.andWhere("registration.occurrence_id = :occurrenceId", { occurrenceId: query.occurrenceId }); if (query.customerId) builder.andWhere("registration.customer_id = :customerId", { customerId: query.customerId }); if (query.status) builder.andWhere("registration.status = :status", { status: query.status }); builder.orderBy("registration.created_at", "DESC").take(query.limit + 1); const rows = await builder.getMany(); const page = rows.slice(0, query.limit); return { items: await Promise.all(page.map((row) => this.registrationDto(this.dataSource.manager, row, actor))), nextCursor: rows.length > query.limit ? page.at(-1)?.createdAt.toISOString() ?? null : null } }
  async getRegistration(idOrCode: string, actor: SessionUser) { this.assert(actor, "canView"); return this.registrationDto(this.dataSource.manager, await this.findRegistration(this.dataSource.manager, idOrCode), actor) }
  async createRegistration(input: ProgramRegistrationCreate, actor: SessionUser, requestId: string) {
    this.assert(actor, "canCreate")
    return this.dataSource.transaction(async (manager) => {
      const scope = "program-registration:create", fingerprint = canonicalSha256({ command: "program-registration.create", input })
      const replay = await this.transitionReplay(manager, scope, input.operationId, input.idempotencyKey, fingerprint); if (replay) return replay
      const occurrence = (await this.lockOccurrences(manager, [input.occurrenceId]))[0]
      if (!occurrence) throw new NotFoundException({ code: "PROGRAM_OCCURRENCE_NOT_FOUND", message: "Проведение программы не найдено" })
      await this.assertRegistrationCapacity(manager, occurrence, input.participantCount, null)
      const priced = await this.hasExactProgramOffering(manager, occurrence.templateId)
      if (priced && ((input.total?.amountMinor ?? 0) !== 0 || (input.discount?.amountMinor ?? 0) !== 0 || input.status !== "new")) throw new UnprocessableEntityException({ code: "PROGRAM_QUOTE_REQUIRED", message: "Цена новой регистрации фиксируется только при принятии server quote" })
      if (!priced && !input.total) throw new UnprocessableEntityException({ code: "LEGACY_TOTAL_REQUIRED", message: "Для legacy программы нужна сумма" })
      const total = priced ? { amountMinor: 0, currency: occurrence.currency } : input.total!
      const discount = priced ? { amountMinor: 0, currency: occurrence.currency } : input.discount ?? { amountMinor: 0, currency: total.currency }
      if (discount.currency !== total.currency) throw new ConflictException({ code: "CURRENCY_MISMATCH", message: "Валюта регистрации должна совпадать" })
      const row = manager.create(ProgramRegistrationEntity, { id: randomUUID(), code: input.code ?? `PR-${await this.next(manager, "program_registration_code_seq")}`, occurrenceId: occurrence.id, customerId: input.customerId, phone: input.phone, participantCount: input.participantCount, participantNames: input.participantNames, totalAmount: total.amountMinor, discountAmount: discount.amountMinor, paidAmount: 0, currency: total.currency, pricingMode: priced ? "quote_required" : "legacy_unpriced", status: input.status, promo: input.promo, source: input.source, comment: input.comment, createdBy: actor.id, updatedBy: actor.id, archivedAt: null })
      const saved = await manager.save(row); const response = await this.registrationDto(manager, saved, actor); await this.mutate(manager, saved, "program_registration", "created", actor.id, requestId, response); await this.rememberTransition(manager, scope, input.operationId, input.idempotencyKey, fingerprint, response); return response
    })
  }
  async updateRegistration(idOrCode: string, input: ProgramRegistrationUpdate, actor: SessionUser, requestId: string) {
    this.assert(actor, "canEdit"); const resolved = await this.findRegistration(this.dataSource.manager, idOrCode)
    return this.dataSource.transaction(async (manager) => {
      const scope = `program-registration:${resolved.id}:update`, fingerprint = canonicalSha256({ command: "program-registration.update", registrationId: resolved.id, input })
      const replay = await this.transitionReplay(manager, scope, input.operationId, input.idempotencyKey, fingerprint); if (replay) return replay
      const current = await manager.createQueryBuilder(ProgramRegistrationEntity, "registration").setLock("pessimistic_write").where("registration.id = :id", { id: resolved.id }).getOneOrFail(); this.assertVersion(current, input.version)
      const accepted = await manager.findOne(AcceptedOfferingQuoteLinkEntity, { where: { programRegistrationId: current.id } })
      if (accepted && (input.occurrenceId !== undefined || input.participantCount !== undefined || input.total !== undefined || input.discount !== undefined)) throw new ConflictException({ code: "ACCEPTED_QUOTE_IMMUTABLE", message: "Параметры принятого quote неизменяемы" })
      if (current.pricingMode === "quote_required" && (input.total !== undefined || input.discount !== undefined)) throw new UnprocessableEntityException({ code: "PROGRAM_QUOTE_REQUIRED", message: "Цена priced registration изменяется только server quote" })
      const targetOccurrenceId = input.occurrenceId ?? current.occurrenceId
      const target = (await this.lockOccurrences(manager, [current.occurrenceId, targetOccurrenceId])).find((item) => item.id === targetOccurrenceId)!
      if (targetOccurrenceId !== current.occurrenceId) { const targetMode = await this.hasExactProgramOffering(manager, target.templateId) ? "quote_required" : "legacy_unpriced"; if (targetMode !== current.pricingMode) throw new ConflictException({ code: "PROGRAM_PRICING_MODE_MOVE_CONFLICT", message: "Перенос между priced и legacy программами запрещён" }) }
      if (targetOccurrenceId !== current.occurrenceId || input.participantCount !== undefined && input.participantCount !== current.participantCount) await this.assertRegistrationCapacity(manager, target, input.participantCount ?? current.participantCount, current.id)
      const patch: Partial<ProgramRegistrationEntity> = { ...(input.occurrenceId === undefined ? {} : { occurrenceId: input.occurrenceId }), ...(input.customerId === undefined ? {} : { customerId: input.customerId }), ...(input.phone === undefined ? {} : { phone: input.phone }), ...(input.participantCount === undefined ? {} : { participantCount: input.participantCount }), ...(input.participantNames === undefined ? {} : { participantNames: input.participantNames }), ...(input.total === undefined ? {} : { totalAmount: input.total.amountMinor, currency: input.total.currency }), ...(input.discount === undefined ? {} : { discountAmount: input.discount.amountMinor }), ...(input.promo === undefined ? {} : { promo: input.promo }), ...(input.source === undefined ? {} : { source: input.source }), ...(input.comment === undefined ? {} : { comment: input.comment }), updatedBy: actor.id }
      const result = await manager.createQueryBuilder().update(ProgramRegistrationEntity).set({ ...patch, version: () => '"version" + 1', updatedAt: () => "now()" }).where("id = :id AND version = :version", { id: current.id, version: input.version }).execute(); if (result.affected !== 1) throw this.versionConflict(current)
      const saved = await manager.findOneByOrFail(ProgramRegistrationEntity, { id: current.id }); const response = await this.registrationDto(manager, saved, actor); await this.mutate(manager, saved, "program_registration", "updated", actor.id, requestId, response); await this.rememberTransition(manager, scope, input.operationId, input.idempotencyKey, fingerprint, response); return response
    })
  }
  async transitionRegistration(idOrCode: string, input: ProgramRegistrationTransition, actor: SessionUser, requestId: string) { this.assert(actor, "canChangeStatus"); return this.transitionEntity(idOrCode, input, actor, requestId, "registration") }
  async archiveRegistration(idOrCode: string, input: ProgramRegistrationArchive, actor: SessionUser, requestId: string) { return this.archiveEntity(idOrCode, input, actor, requestId, "registration") }

  private templateDto(row: ProgramTemplateEntity, actor: SessionUser) { return { id: row.id, version: row.version, code: row.code, name: row.name, categoryId: row.categoryId, durationMinutes: row.durationMinutes, minimumParticipants: row.minimumParticipants, participantLimit: row.participantLimit, registrationCloseHours: row.registrationCloseHours === null ? null : Number(row.registrationCloseHours), basePrice: { amountMinor: row.basePriceAmount, currency: row.currency }, description: row.description, publication: row.publication, published: row.publication === "published", assigneeIds: row.assigneeIds, stages: (row.stages ?? []).map((stage) => ({ id: String(stage.id), name: String(stage.name), durationMinutes: Number(stage.durationMinutes), comment: String(stage.comment ?? "") })), nextOccurrence: null, archived: row.archivedAt !== null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), capabilities: this.capabilities(actor, ["canView", "canCreate", "canEdit", "canArchive", "canChangeStatus"]) } }
  private async occurrenceDto(manager: EntityManager, row: ProgramOccurrenceEntity, actor: SessionUser) { const aggregates = await manager.getRepository(ProgramRegistrationEntity).createQueryBuilder("registration").select("COALESCE(SUM(registration.participant_count),0)", "participants").addSelect("COUNT(registration.id)", "registrations").addSelect("COALESCE(SUM(registration.total_amount),0)", "revenue").addSelect("COALESCE(SUM(registration.paid_amount),0)", "paid").where("registration.occurrence_id = :id AND registration.archived_at IS NULL AND registration.status <> 'cancelled'", { id: row.id }).getRawOne<{ participants: string; registrations: string; revenue: string; paid: string }>(); return { id: row.id, version: row.version, code: row.code, templateId: row.templateId, name: row.name, startsAt: row.startsAt.toISOString(), endsAt: row.endsAt.toISOString(), participantLimit: row.participantLimit, registrationLimit: row.registrationLimit, participantCount: Number(aggregates?.participants ?? 0), registrationCount: Number(aggregates?.registrations ?? 0), revenue: { amountMinor: Number(aggregates?.revenue ?? 0), currency: row.currency }, paid: { amountMinor: Number(aggregates?.paid ?? 0), currency: row.currency }, status: row.status, comment: row.comment, assigneeIds: row.assigneeIds, archived: row.archivedAt !== null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), capabilities: this.capabilities(actor, ["canView", "canCreate", "canEdit", "canArchive", "canChangeStatus", "canOverrideConflict"]) } }
  private async registrationDto(manager: EntityManager, row: ProgramRegistrationEntity, actor: SessionUser) {
    const link = await manager.findOne(AcceptedOfferingQuoteLinkEntity, { where: { programRegistrationId: row.id } })
    let acceptedQuote = null
    if (link) {
      const quote = await manager.findOneByOrFail(OfferingQuoteSnapshotEntity, { id: link.quoteSnapshotId })
      const result = ProgramRegistrationQuoteResultSchema.parse(quote.resultPayload)
      acceptedQuote = { quoteId: quote.id, acceptedAt: link.acceptedAt.toISOString(), total: result.total, lines: result.lines, addOns: result.inputs.addOns }
    }
    return { id: row.id, version: row.version, code: row.code, occurrenceId: row.occurrenceId, customerId: row.customerId, phone: row.phone, participantCount: row.participantCount, participantNames: row.participantNames, total: { amountMinor: row.totalAmount, currency: row.currency }, discount: { amountMinor: row.discountAmount, currency: row.currency }, paid: { amountMinor: row.paidAmount, currency: row.currency }, pricingMode: row.pricingMode as "legacy_unpriced" | "quote_required", acceptedQuote, status: row.status, promo: row.promo, source: row.source, comment: row.comment, archived: row.archivedAt !== null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), capabilities: this.capabilities(actor, ["canView", "canCreate", "canEdit", "canArchive", "canChangeStatus", "canAddPayment", "canRefund"]) }
  }
  private capabilities(actor: SessionUser, keys: string[]) { return Object.fromEntries(keys.map((key) => [key, actor.capabilities[key as keyof SessionUser["capabilities"]] === true])) }
  private assert(actor: SessionUser, key: keyof SessionUser["capabilities"]) { if (!actor.capabilities[key]) throw new ForbiddenException({ code: "PERMISSION_DENIED", message: `Capability ${key} is required` }) }
  private assertVersion(row: { id: string; version: number }, expected: number) { if (row.version !== expected) throw this.versionConflict(row) }
  private versionConflict(row: { id: string; version: number }) { return new ConflictException({ code: "VERSION_CONFLICT", message: "Запись была изменена другим сотрудником", details: { entityId: row.id, serverVersion: row.version } }) }
  private async findTemplate(manager: EntityManager, idOrCode: string) { const row = await manager.getRepository(ProgramTemplateEntity).findOne({ where: /^[0-9a-f-]{36}$/i.test(idOrCode) ? { id: idOrCode } : { code: idOrCode } }); if (!row) throw new NotFoundException({ code: "PROGRAM_TEMPLATE_NOT_FOUND", message: "Шаблон программы не найден" }); return row }
  private async findOccurrence(manager: EntityManager, idOrCode: string) { const row = await manager.getRepository(ProgramOccurrenceEntity).findOne({ where: /^[0-9a-f-]{36}$/i.test(idOrCode) ? { id: idOrCode } : { code: idOrCode } }); if (!row) throw new NotFoundException({ code: "PROGRAM_OCCURRENCE_NOT_FOUND", message: "Проведение программы не найдено" }); return row }
  private async findRegistration(manager: EntityManager, idOrCode: string) { const row = await manager.getRepository(ProgramRegistrationEntity).findOne({ where: /^[0-9a-f-]{36}$/i.test(idOrCode) ? { id: idOrCode } : { code: idOrCode } }); if (!row) throw new NotFoundException({ code: "PROGRAM_REGISTRATION_NOT_FOUND", message: "Регистрация не найдена" }); return row }
  private async next(manager: EntityManager, sequence: string) { const result = await manager.query(`SELECT nextval('${sequence}')::text AS nextval`) as Array<{ nextval: string }>; return result[0]!.nextval }
  private async lockOccurrences(manager: EntityManager, ids: readonly string[]) { const unique = [...new Set(ids)].sort(); return manager.createQueryBuilder(ProgramOccurrenceEntity, "occurrence").setLock("pessimistic_write").where("occurrence.id IN (:...ids)", { ids: unique }).orderBy("occurrence.id", "ASC").getMany() }
  private async assertOccurrenceLimits(manager: EntityManager, occurrenceId: string, participantLimit: number, registrationLimit: number) { const aggregate = await manager.getRepository(ProgramRegistrationEntity).createQueryBuilder("registration").select("COALESCE(SUM(participant_count),0)", "participants").addSelect("COUNT(id)", "registrations").where("occurrence_id = :occurrenceId AND archived_at IS NULL AND status <> 'cancelled'", { occurrenceId }).getRawOne<{ participants: string; registrations: string }>(); if (participantLimit < Number(aggregate?.participants ?? 0) || registrationLimit < Number(aggregate?.registrations ?? 0)) throw new ConflictException({ code: "CAPACITY_EXCEEDED", message: "Лимиты не могут быть ниже текущей занятости" }) }
  private async hasExactProgramOffering(manager: EntityManager, templateId: string) { const rows = await manager.createQueryBuilder(CatalogOfferingEntity, "offering").innerJoin(OfferingBindingEntity, "binding", "binding.offering_id = offering.id AND binding.role = 'primary' AND binding.archived_at IS NULL").where("offering.kind = 'program' AND offering.archived_at IS NULL AND offering.state <> 'archived' AND binding.program_template_id = :templateId", { templateId }).getMany(); if (rows.length > 1) throw new ConflictException({ code: "PROGRAM_OFFERING_AMBIGUOUS", message: "Program offering не найден однозначно" }); return rows.length === 1 }
  private async assertRegistrationCapacity(manager: EntityManager, occurrence: ProgramOccurrenceEntity, count: number, excludeRegistrationId: string | null) { if (["closed", "completed", "cancelled"].includes(occurrence.status)) throw new ConflictException({ code: "INVALID_STATE_TRANSITION", message: "Регистрация закрыта для этого проведения" }); const builder = manager.getRepository(ProgramRegistrationEntity).createQueryBuilder("registration").select("COALESCE(SUM(participant_count),0)", "participants").addSelect("COUNT(id)", "registrations").where("occurrence_id = :id AND archived_at IS NULL AND status <> 'cancelled'", { id: occurrence.id }); if (excludeRegistrationId) builder.andWhere("id <> :excludeRegistrationId", { excludeRegistrationId }); const aggregate = await builder.getRawOne<{ participants: string; registrations: string }>(); if (Number(aggregate?.participants ?? 0) + count > occurrence.participantLimit || Number(aggregate?.registrations ?? 0) + 1 > occurrence.registrationLimit) throw new ConflictException({ code: "CAPACITY_EXCEEDED", message: "В проведении недостаточно мест" }) }
  private async mutate(manager: EntityManager, entity: { id: string; version: number }, entityType: string, action: string, actorId: string, requestId: string, changes: unknown) { const now = new Date(); await manager.getRepository(ChangeLogEntity).save(manager.create(ChangeLogEntity, { id: randomUUID(), entityType, entityId: entity.id, action, actorId, requestId, changes: changes as Record<string, unknown>, createdAt: now })); await manager.getRepository(OutboxEventEntity).save(manager.create(OutboxEventEntity, { id: randomUUID(), topic: `${entityType}.${action}`, aggregateType: entityType, aggregateId: entity.id, payload: { id: entity.id, version: entity.version }, availableAt: now, processedAt: null, attempts: 0, createdAt: now })) }
  private async replay(manager: EntityManager, scope: string, operationId: string, idempotencyKey: string) { const row = await manager.getRepository(IdempotencyKeyEntity).createQueryBuilder("key").where("key.scope = :scope", { scope }).andWhere(new Brackets((q) => q.where("key.operation_id = :operationId", { operationId }).orWhere("key.idempotency_key = :idempotencyKey", { idempotencyKey }))).getOne(); if (!row) return null; if (row.responseBody) return row.responseBody; throw new ConflictException({ code: "IDEMPOTENCY_CONFLICT", message: "Операция уже выполняется" }) }
  private async remember(manager: EntityManager, scope: string, operationId: string, idempotencyKey: string, response: unknown) { await manager.getRepository(IdempotencyKeyEntity).save(manager.create(IdempotencyKeyEntity, { id: randomUUID(), scope, operationId, idempotencyKey, requestHash: JSON.stringify(response), responseStatus: 200, responseBody: response as Record<string, unknown>, createdAt: new Date() })) }
  private async transitionEntity(idOrCode: string, input: { version: number; operationId: string; idempotencyKey: string; status: string; quoteAcceptance?: unknown }, actor: SessionUser, requestId: string, kind: "occurrence" | "registration") {
    const resolved = kind === "occurrence" ? await this.findOccurrence(this.dataSource.manager, idOrCode) : await this.findRegistration(this.dataSource.manager, idOrCode)
    return this.dataSource.transaction(async (manager) => {
      const scope = `program-${kind}:${resolved.id}:transition`
      const requestHash = canonicalSha256({ command: "program.transition", kind, entityId: resolved.id, input })
      const replay = await this.transitionReplay(manager, scope, input.operationId, input.idempotencyKey, requestHash)
      if (replay) return replay
      const entity = kind === "occurrence"
        ? await manager.createQueryBuilder(ProgramOccurrenceEntity, "occurrence").setLock("pessimistic_write").where("occurrence.id = :id", { id: resolved.id }).getOneOrFail()
        : await manager.createQueryBuilder(ProgramRegistrationEntity, "registration").setLock("pessimistic_write").where("registration.id = :id", { id: resolved.id }).getOneOrFail()
      this.assertVersion(entity, input.version)
      const allowed: Record<string, string[]> = kind === "occurrence" ? { draft: ["open", "cancelled"], open: ["closed", "completed", "cancelled"], closed: ["open", "completed", "cancelled"], completed: [], cancelled: [] } : { new: ["confirmed", "cancelled"], confirmed: ["paid", "cancelled"], paid: ["visited", "cancelled"], visited: [], cancelled: [] }
      if (!allowed[entity.status]?.includes(input.status)) throw new ConflictException({ code: "INVALID_STATE_TRANSITION", message: `Нельзя перевести запись из ${entity.status} в ${input.status}` })
      let prepared: Awaited<ReturnType<OperationalQuoteAcceptanceService["prepareProgramRegistration"]>> | null = null
      if (kind === "registration" && input.status === "confirmed") {
        const registration = entity as ProgramRegistrationEntity
        const occurrence = (await this.lockOccurrences(manager, [registration.occurrenceId]))[0]!
        await this.assertRegistrationCapacity(manager, occurrence, registration.participantCount, registration.id)
        if (registration.pricingMode === "quote_required" && !input.quoteAcceptance) throw new UnprocessableEntityException({ code: "PROGRAM_QUOTE_REQUIRED", message: "Для подтверждения priced registration нужен occurrence quote" })
        if (registration.pricingMode === "legacy_unpriced" && input.quoteAcceptance) throw new UnprocessableEntityException({ code: "QUOTE_TARGET_UNSUPPORTED", message: "Legacy registration не связана с exact program offering" })
        if (input.quoteAcceptance) prepared = await this.quoteAcceptance.prepareProgramRegistration(manager, registration, occurrence, (input.quoteAcceptance as { quoteSnapshotId: string }).quoteSnapshotId)
      }
      const type = kind === "occurrence" ? ProgramOccurrenceEntity : ProgramRegistrationEntity
      const quotePatch = prepared ? { totalAmount: prepared.result.total.amountMinor, discountAmount: 0, currency: prepared.result.currency } : {}
      const result = await manager.createQueryBuilder().update(type).set({ status: input.status, ...quotePatch, updatedBy: actor.id, version: () => '"version" + 1', updatedAt: () => "now()" }).where("id = :id AND version = :version", { id: entity.id, version: input.version }).execute()
      if (result.affected !== 1) throw this.versionConflict(entity)
      const saved = await manager.findOneByOrFail(type, { id: entity.id })
      if (prepared) await this.quoteAcceptance.recordProgramRegistration(manager, saved as unknown as ProgramRegistrationEntity, prepared, actor, requestId, input.operationId)
      const response = kind === "occurrence" ? await this.occurrenceDto(manager, saved as unknown as ProgramOccurrenceEntity, actor) : await this.registrationDto(manager, saved as unknown as ProgramRegistrationEntity, actor)
      await this.mutate(manager, saved, `program_${kind}`, "transitioned", actor.id, requestId, { from: entity.status, to: input.status, after: response })
      await this.rememberTransition(manager, scope, input.operationId, input.idempotencyKey, requestHash, response)
      return response
    })
  }

  private async transitionReplay(manager: EntityManager, scope: string, operationId: string, idempotencyKey: string, requestHash: string) {
    for (const lock of [`key:${scope}:${idempotencyKey}`, `operation:${scope}:${operationId}`].sort()) await manager.query("SELECT pg_advisory_xact_lock(hashtextextended($1, 0))", [lock])
    const row = await manager.getRepository(IdempotencyKeyEntity).createQueryBuilder("key").where("key.scope = :scope", { scope }).andWhere(new Brackets((query) => query.where("key.operation_id = :operationId", { operationId }).orWhere("key.idempotency_key = :idempotencyKey", { idempotencyKey }))).getOne()
    if (!row) return null
    if (row.operationId !== operationId || row.idempotencyKey !== idempotencyKey || row.requestHash !== requestHash) throw new ConflictException({ code: "IDEMPOTENCY_CONFLICT", message: "Ключ идемпотентности уже использован с другими данными" })
    if (row.responseBody) return row.responseBody
    throw new ConflictException({ code: "IDEMPOTENCY_CONFLICT", message: "Операция уже выполняется" })
  }

  private async rememberTransition(manager: EntityManager, scope: string, operationId: string, idempotencyKey: string, requestHash: string, response: unknown) {
    await manager.getRepository(IdempotencyKeyEntity).save(manager.create(IdempotencyKeyEntity, { id: randomUUID(), scope, operationId, idempotencyKey, requestHash, responseStatus: 200, responseBody: response as Record<string, unknown>, createdAt: new Date() }))
  }
  private async archiveEntity(idOrCode: string, input: { version: number; operationId: string; idempotencyKey: string }, actor: SessionUser, requestId: string, kind: "template" | "occurrence" | "registration") { this.assert(actor, "canArchive"); return this.dataSource.transaction(async (manager) => { const entity = kind === "template" ? await this.findTemplate(manager, idOrCode) : kind === "occurrence" ? await this.findOccurrence(manager, idOrCode) : await this.findRegistration(manager, idOrCode); this.assertVersion(entity, input.version); const type = kind === "template" ? ProgramTemplateEntity : kind === "occurrence" ? ProgramOccurrenceEntity : ProgramRegistrationEntity; const result = await manager.createQueryBuilder().update(type).set({ archivedAt: new Date(), updatedBy: actor.id, version: () => '"version" + 1', updatedAt: () => "now()" }).where("id = :id AND version = :version", { id: entity.id, version: input.version }).execute(); if (result.affected !== 1) throw this.versionConflict(entity); const saved = await manager.findOneByOrFail(type, { id: entity.id }); const response = kind === "template" ? this.templateDto(saved as unknown as ProgramTemplateEntity, actor) : kind === "occurrence" ? await this.occurrenceDto(manager, saved as unknown as ProgramOccurrenceEntity, actor) : await this.registrationDto(manager, saved as unknown as ProgramRegistrationEntity, actor); await this.mutate(manager, saved, `program_${kind}`, "archived", actor.id, requestId, response); return response }) }
}
